package com.app.form.herramientas;

import com.app.clases.ClaseCampos;
import com.app.clases.ClaseEncriptacion;
import com.app.clases.ClaseTeclas;
import com.app.clases.ClaseTextoIO;
import com.app.config.MensajeSistema;
import com.app.config.Propiedades;
import com.app.form.Especiales.frm_Padre;
import com.app.form.Especiales.frm_Principal;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Diego
 */
public class frm_Configuracion extends frm_Padre {

    private final boolean Archivo, Conex;
    private Propiedades propiedades = null;

    public frm_Configuracion(boolean archivo, boolean conex) {
        initComponents();
        this.setName("Config");
        if (archivo) {
            this.jLabel1.setText("Archivo de Configuración encontrado...");
        } else {
            this.jLabel1.setText("No se encontro el archivo de configuración...");
        }
        if (conex) {
            this.jLabel2.setText("Se realizo con exito la conexión con el Servidor");
        } else {
            this.jLabel2.setText("No se pudo concretar la conexión con el Servidor...");
        }
        this.Archivo = archivo;
        this.Conex = conex;
        if (archivo) {
            try {
                propiedades = new Propiedades();
            } catch (IOException ex) {
                MensajeSistema.setIOException(this, "No se pudo abrir el archivo de configuracion", ex);
            }
        }
        this.limpiarHoja2();
        this.cargarCombo();
        this.jTabbedPane1.setSelectedIndex(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanelTitulo = new javax.swing.JPanel();
        textTitulo = new javax.swing.JLabel();
        jLabelFechaHora1 = new com.app.paleta.JLabelFechaHora();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnConexion = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btnCrear = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtHost = new com.app.paleta.txtTexto();
        txtPort = new com.app.paleta.txtNumeros();
        jLabel5 = new javax.swing.JLabel();
        txtUser = new com.app.paleta.txtTexto();
        jLabel6 = new javax.swing.JLabel();
        txtPass = new com.app.paleta.txtPassword();
        jLabel7 = new javax.swing.JLabel();
        txtBD = new com.app.paleta.txtTexto();
        jLabel8 = new javax.swing.JLabel();
        txtImpresora = new com.app.paleta.txtTexto();
        jLabel9 = new javax.swing.JLabel();
        cboDecoracion = new javax.swing.JComboBox();
        jPanel4 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanelTitulo.setBackground(new java.awt.Color(204, 204, 204));
        jPanelTitulo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelTitulo.setMaximumSize(new java.awt.Dimension(486, 60));
        jPanelTitulo.setMinimumSize(new java.awt.Dimension(486, 60));

        textTitulo.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        textTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textTitulo.setText("CONFIGURACION DEL SISTEMA");

        javax.swing.GroupLayout jPanelTituloLayout = new javax.swing.GroupLayout(jPanelTitulo);
        jPanelTitulo.setLayout(jPanelTituloLayout);
        jPanelTituloLayout.setHorizontalGroup(
            jPanelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelTituloLayout.setVerticalGroup(
            jPanelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("jLabel1");

        jLabel2.setText("jLabel1");

        btnConexion.setText("Probar Conexión");
        btnConexion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConexionActionPerformed(evt);
            }
        });

        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(btnConexion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 87, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(54, 54, 54)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConexion)
                    .addComponent(jButton1))
                .addContainerGap(70, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Información", jPanel2);

        btnCrear.setText("Crear Configuración");
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });

        btnLimpiar.setText("Limpiar Campos");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Host:");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Port:");

        txtHost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHostActionPerformed(evt);
            }
        });

        txtPort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPortActionPerformed(evt);
            }
        });

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("User:");

        txtUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserActionPerformed(evt);
            }
        });

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Pass:");

        txtPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPassActionPerformed(evt);
            }
        });

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("BD:");

        txtBD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBDActionPerformed(evt);
            }
        });

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Impresora:");

        txtImpresora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtImpresoraActionPerformed(evt);
            }
        });

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Decoracion:");

        cboDecoracion.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cboDecoracionFocusLost(evt);
            }
        });
        cboDecoracion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cboDecoracionKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnCrear)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLimpiar))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPort, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(54, 54, 54)
                                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtBD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtPass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtHost, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtImpresora, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                            .addComponent(cboDecoracion, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtHost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(txtImpresora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(cboDecoracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtBD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCrear)
                    .addComponent(btnLimpiar))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Archivo de Configuración", jPanel3);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 481, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 196, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Configuracion de Usuarios", jPanel4);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTabbedPane1)
                    .addComponent(jPanelTitulo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelFechaHora1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelFechaHora1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        this.crearArchiConfiguracion();
    }//GEN-LAST:event_btnCrearActionPerformed

    private void btnConexionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConexionActionPerformed
        frm_ping ven = new frm_ping("");
        ven.setLocation((frm_Principal.escritorio.getSize().width - ven.getSize().width) / 2,
                (frm_Principal.escritorio.getSize().height - ven.getSize().height) / 2);
        frm_Principal.escritorio.add(ven);
        try {
            ven.toFront();
            ven.setSelected(true);
        } catch (Exception ex) {
        }
    }//GEN-LAST:event_btnConexionActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (new MensajeSistema().Salir()) {
            System.exit(0);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        this.limpiarHoja2();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void txtHostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHostActionPerformed
        int valor = this.txtHost.verificarVacioConMsj();
        if (valor == 0) {
            this.txtPort.setNumero("3306");
            this.txtPort.grabFocus();
        } else if (valor == 1) {
            this.limpiarHoja2();
        }
    }//GEN-LAST:event_txtHostActionPerformed

    private void txtPortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPortActionPerformed
        if (this.txtPort.getNumeroInt() <= 0) {
            int msn = MensajeSistema.MensajeOpciones(this, "No puede dejar vacio este campo...\nDesea Reintentar???",
                    new Object[]{"Si, Reintentar", "No, Cancelar"}, 0);
            if (msn == 0) {
                this.txtPort.setNumero("3306");
                this.txtPort.grabFocus();
            } else {
                this.limpiarHoja2();
            }
        } else {
            this.txtUser.grabFocus();
        }
    }//GEN-LAST:event_txtPortActionPerformed

    private void txtUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserActionPerformed
        int valor = this.txtUser.verificarVacioConMsj();
        if (valor == 0) {
            this.txtPass.grabFocus();
        } else if (valor == 1) {
            this.limpiarHoja2();
        }
    }//GEN-LAST:event_txtUserActionPerformed

    private void txtPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPassActionPerformed
        int valor = this.txtPass.verificarVacioConMsj();
        if (valor == 0) {
            this.txtBD.grabFocus();
        } else if (valor == 1) {
            this.limpiarHoja2();
        }
    }//GEN-LAST:event_txtPassActionPerformed

    private void txtBDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBDActionPerformed
        int valor = this.txtBD.verificarVacioConMsj();
        if (valor == 0) {
            this.txtImpresora.grabFocus();
        } else if (valor == 1) {
            this.limpiarHoja2();
        }
    }//GEN-LAST:event_txtBDActionPerformed

    private void txtImpresoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtImpresoraActionPerformed
        int valor = this.txtImpresora.verificarVacioConMsj();
        if (valor == 0) {
            this.cboDecoracion.grabFocus();
        } else if (valor == 1) {
            this.limpiarHoja2();
        }
    }//GEN-LAST:event_txtImpresoraActionPerformed

    private void cboDecoracionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cboDecoracionFocusLost
        this.btnCrear.grabFocus();
    }//GEN-LAST:event_cboDecoracionFocusLost

    private void cboDecoracionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cboDecoracionKeyPressed
        if (evt.getKeyCode() == ClaseTeclas.VK_ENTER()) {
            this.cboDecoracion.transferFocus();
        }
    }//GEN-LAST:event_cboDecoracionKeyPressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConexion;
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JComboBox cboDecoracion;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private com.app.paleta.JLabelFechaHora jLabelFechaHora1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanelTitulo;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel textTitulo;
    private com.app.paleta.txtTexto txtBD;
    private com.app.paleta.txtTexto txtHost;
    private com.app.paleta.txtTexto txtImpresora;
    private com.app.paleta.txtPassword txtPass;
    private com.app.paleta.txtNumeros txtPort;
    private com.app.paleta.txtTexto txtUser;
    // End of variables declaration//GEN-END:variables

    private void cargarCombo() {
        this.cboDecoracion.removeAllItems();
        this.cboDecoracion.addItem("AutumnSkin");
        this.cboDecoracion.addItem("BusinessSkin");
        this.cboDecoracion.addItem("BusinessBlueSteelSkin");
        this.cboDecoracion.addItem("BusinessBlackSteelSkin");
        this.cboDecoracion.addItem("ChallengerDeepSkin");
        this.cboDecoracion.addItem("CremeCoffeeSkin");
        this.cboDecoracion.addItem("CremeSkin");
        this.cboDecoracion.addItem("EmeraldDuskSkin");
        this.cboDecoracion.addItem("FieldOfWheatSkin");
        this.cboDecoracion.addItem("FindingNemoSkin");
        this.cboDecoracion.addItem("GreenMagicSkin");
        this.cboDecoracion.addItem("MagmaSkin");
        this.cboDecoracion.addItem("MangoSkin");
        this.cboDecoracion.addItem("MistAquaSkin");
        this.cboDecoracion.addItem("MistSilverSkin");
        this.cboDecoracion.addItem("ModerateSkin");
        this.cboDecoracion.addItem("NebulaSkin");
        this.cboDecoracion.addItem("OfficeBlue2007Skin");
        this.cboDecoracion.addItem("OfficeSilver2007Skin");
        this.cboDecoracion.addItem("RavenSkin");
        this.cboDecoracion.addItem("SaharaSkin");
        this.cboDecoracion.addItem("SubstanceSkin");
        this.cboDecoracion.setSelectedIndex(0);
    }

    private void limpiarHoja2() {
        if (this.Archivo) {
            this.txtHost.setText(propiedades.getHost());
            this.txtPort.setText(propiedades.getPort());
            this.txtUser.setText(propiedades.getUser());
            this.txtPass.setText(ClaseEncriptacion.descifrarTexto(propiedades.getPass()));
            this.txtBD.setText(propiedades.getBD());
            this.txtImpresora.setText(propiedades.getImpresora());
            try {
                this.cboDecoracion.setSelectedItem(propiedades.getDecoracion());
            } catch (Exception ex) {
                this.cboDecoracion.setSelectedIndex(0);
            }
        } else {
            this.txtHost.setText("");
            this.txtPort.setText("");
            this.txtUser.setText("");
            this.txtPass.setText("");
            this.txtBD.setText("");
            this.txtImpresora.setText("");
            this.cboDecoracion.removeAllItems();
        }
    }

    private void crearArchiConfiguracion() {
        if (ClaseCampos.setValidate(jPanel3)) {
            MensajeSistema.MensajeVarios(this, "Existen campos que estan vacios...", MensajeSistema.ERROR_MESSAGE());
            this.txtHost.grabFocus();
        } else {
            if (this.Archivo) {
                propiedades.setHost(this.txtHost.getText().trim());
                propiedades.setPort(this.txtPort.getText().trim());
                propiedades.setUser(this.txtUser.getText().trim());
                propiedades.setPass(ClaseEncriptacion.cifrarTexto(this.txtPass.getText().trim()));
                propiedades.setBD(this.txtBD.getText().trim());
                propiedades.setImpresora(this.txtImpresora.getText().trim());
                propiedades.setDecoracion(this.cboDecoracion.getSelectedItem().toString().trim());
                MensajeSistema.MensajeVarios(this, "Archivo de Configuración Actualizado...\n\nSalga y vuelva abrir el programa...\n", MensajeSistema.INFORMATION_MESSAGE());
                this.jTabbedPane1.setSelectedIndex(0);
            } else {
                String texto = "host=" + this.txtHost.getText().trim() + "\n"
                        + "port=" + this.txtPort.getText().trim() + "\n"
                        + "user=" + this.txtUser.getText().trim() + "\n"
                        + "pass=" + ClaseEncriptacion.cifrarTexto(this.txtPass.getText().trim()) + "\n"
                        + "bd=" + this.txtBD.getText().trim() + "\n"
                        + "impresora=" + this.txtImpresora.getText().trim() + "\n"
                        + "decoracion=" + this.cboDecoracion.getSelectedItem().toString().trim();
                try {
                    ClaseTextoIO.escribirArchivoNuevo("configuracion.properties", texto);
                    MensajeSistema.MensajeVarios(this, "Archivo de Configuración creado...\n\nSalga y vuelva abrir el programa...\n", MensajeSistema.INFORMATION_MESSAGE());
                    this.jTabbedPane1.setSelectedIndex(0);
                } catch (IOException ex) {
                    MensajeSistema.setIOException(this, "Se produjo un error al Crear el archivo de configuración", ex);
                }
            }
        }
    }
}
