package com.app.form.herramientas;

import com.app.clases.ClaseCampos;
import com.app.clases.ClaseEncriptacion;
import com.app.clases.ClaseTeclas;
import com.app.clases.ClaseTextoIO;
import com.app.config.MensajeSistema;
import com.app.config.Propiedades;
import com.app.form.Especiales.frm_Padre;
import static com.app.form.Especiales.frm_Padre.cod_empresa;
import com.app.form.Especiales.frm_Principal;
import java.io.IOException;

/**
 *
 * @author Diego
 */
public class frm_Configuracion extends frm_Padre {

    private final boolean Archivo, Conex;
    private Propiedades propiedades = null;

    public frm_Configuracion(boolean archivo, boolean conex) {
        initComponents();
        this.setName("Config");
        if (archivo) {
            this.jLabel1.setText("Archivo de Configuración encontrado...");
        } else {
            this.jLabel1.setText("No se encontro el archivo de configuración...");
        }
        if (conex) {
            this.jLabel2.setText("Se realizo con exito la conexión con el Servidor");
        } else {
            this.jLabel2.setText("No se pudo concretar la conexión con el Servidor...");
        }
        this.Archivo = archivo;
        this.Conex = conex;
        if (archivo) {
            try {
                propiedades = new Propiedades();
            } catch (IOException ex) {
                MensajeSistema.setIOException("No se pudo abrir el archivo de configuracion", ex);
            }
        }
        this.tablaConsutada = "acc_usuarios";
        this.idConsultada = "Usu_Codigo";
        this.descripcionConsultada = "Usu_Nombre";
        this.tituloVentanaActual = "Usuarios";

        this.txtCod_Empresa.setBdTabla("adm_empresas");
        this.txtCod_Empresa.setBdCodigo("Emp_Codigo");
        this.txtCod_Empresa.setBdDescrip("Emp_Descrip");
        this.txtCod_Empresa.setBdTitulo("Empresas");

        this.txtCod_Perfil.setBdTabla("acc_perfiles");
        this.txtCod_Perfil.setBdCodigo("Perf_Codigo");
        this.txtCod_Perfil.setBdDescrip("Perf_Descrip");
        this.txtCod_Perfil.setBdTitulo("Perfiles");

        this.limpiarPag2();
        this.limpiarPag3();
        this.cargarCombo();
//        boolean actPag3 = getConexion.getCOUNTFila(tablaConsutada,
//                new String[]{cod_empresa},
//                new String[]{this.txtCod_Empresa.getText()}) > 0;
        this.jTabbedPane1.setEnabledAt(2, false);
        this.jTabbedPane1.setSelectedIndex(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanelTitulo = new javax.swing.JPanel();
        textTitulo = new javax.swing.JLabel();
        jLabelFechaHora1 = new com.app.paleta.JLabelFechaHora();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnConexion = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btnCrear = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtHost = new com.app.paleta.txtTexto();
        txtPort = new com.app.paleta.txtNumeros();
        jLabel5 = new javax.swing.JLabel();
        txtUser = new com.app.paleta.txtTexto();
        jLabel6 = new javax.swing.JLabel();
        txtPass = new com.app.paleta.txtPassword();
        jLabel7 = new javax.swing.JLabel();
        txtBD = new com.app.paleta.txtTexto();
        jLabel8 = new javax.swing.JLabel();
        txtImpresora = new com.app.paleta.txtTexto();
        jLabel9 = new javax.swing.JLabel();
        cboDecoracion = new com.app.paleta.cbo();
        jPanel4 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        txtCod_Empresa = new com.app.paleta.txtCodigo();
        textEmpresa = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtNom_User = new com.app.paleta.txtTexto();
        jLabel12 = new javax.swing.JLabel();
        txtCod_Perfil = new com.app.paleta.txtCodigo();
        textNomPerfil = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtPass1_User = new com.app.paleta.txtPassword();
        textClave1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtPass2_User = new com.app.paleta.txtPassword();
        textClave2 = new javax.swing.JLabel();
        btnGrabarUser = new com.app.botones.btnGrabar();
        btnCancelarUser = new com.app.botones.btnCancelar();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanelTitulo.setBackground(new java.awt.Color(204, 204, 204));
        jPanelTitulo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelTitulo.setMaximumSize(new java.awt.Dimension(486, 60));
        jPanelTitulo.setMinimumSize(new java.awt.Dimension(486, 60));

        textTitulo.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        textTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textTitulo.setText("CONFIGURACION DEL SISTEMA");

        javax.swing.GroupLayout jPanelTituloLayout = new javax.swing.GroupLayout(jPanelTitulo);
        jPanelTitulo.setLayout(jPanelTituloLayout);
        jPanelTituloLayout.setHorizontalGroup(
            jPanelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelTituloLayout.setVerticalGroup(
            jPanelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("jLabel1");

        jLabel2.setText("jLabel1");

        btnConexion.setText("Probar Conexión");
        btnConexion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConexionActionPerformed(evt);
            }
        });

        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(btnConexion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 87, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(54, 54, 54)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConexion)
                    .addComponent(jButton1))
                .addContainerGap(70, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Información", jPanel2);

        btnCrear.setText("Crear Configuración");
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });

        btnLimpiar.setText("Limpiar Campos");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Host:");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Port:");

        txtHost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHostActionPerformed(evt);
            }
        });

        txtPort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPortActionPerformed(evt);
            }
        });

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("User:");

        txtUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserActionPerformed(evt);
            }
        });

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Pass:");

        txtPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPassActionPerformed(evt);
            }
        });

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("BD:");

        txtBD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBDActionPerformed(evt);
            }
        });

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Impresora:");

        txtImpresora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtImpresoraActionPerformed(evt);
            }
        });

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Decoracion:");

        cboDecoracion.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cboDecoracionFocusLost(evt);
            }
        });
        cboDecoracion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cboDecoracionKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnCrear)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLimpiar))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPort, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(54, 54, 54)
                                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtBD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtPass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtHost, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtImpresora, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                            .addComponent(cboDecoracion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtHost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(txtImpresora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(cboDecoracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtBD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCrear)
                    .addComponent(btnLimpiar))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Archivo de Configuración", jPanel3);

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel14.setText("Empresa:");

        txtCod_Empresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCod_EmpresaActionPerformed(evt);
            }
        });
        txtCod_Empresa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCod_EmpresaKeyPressed(evt);
            }
        });

        textEmpresa.setText("jLabel15");

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setText("Nombre:");

        txtNom_User.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNom_UserActionPerformed(evt);
            }
        });
        txtNom_User.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNom_UserKeyTyped(evt);
            }
        });

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("Perfil:");

        txtCod_Perfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCod_PerfilActionPerformed(evt);
            }
        });
        txtCod_Perfil.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCod_PerfilKeyPressed(evt);
            }
        });

        textNomPerfil.setText("jLabel10");

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("Clave:");

        txtPass1_User.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPass1_UserFocusGained(evt);
            }
        });
        txtPass1_User.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPass1_UserActionPerformed(evt);
            }
        });

        textClave1.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        textClave1.setText("La Clave tiene que ser, min. 5 y max. 15 caracteres. ");

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Repita:");

        txtPass2_User.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPass2_UserFocusGained(evt);
            }
        });
        txtPass2_User.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPass2_UserActionPerformed(evt);
            }
        });

        textClave2.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        textClave2.setText("Repita la contraseña por favor...");

        btnGrabarUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrabarUserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(txtCod_Empresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textEmpresa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(txtNom_User, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(4, 4, 4)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(txtCod_Perfil, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textNomPerfil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtPass1_User, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtPass2_User, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textClave1, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                                    .addComponent(textClave2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(btnGrabarUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCancelarUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCod_Empresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(textEmpresa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtNom_User, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(textNomPerfil)
                        .addComponent(txtCod_Perfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPass1_User, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textClave1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtPass2_User, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textClave2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGrabarUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelarUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Configuracion de Usuarios", jPanel4);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTabbedPane1)
                    .addComponent(jPanelTitulo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelFechaHora1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelFechaHora1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        this.crearArchiConfiguracion();
    }//GEN-LAST:event_btnCrearActionPerformed

    private void btnConexionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConexionActionPerformed
        frm_ping ven = new frm_ping("");
        ven.setLocation((frm_Principal.escritorio.getSize().width - ven.getSize().width) / 2,
                (frm_Principal.escritorio.getSize().height - ven.getSize().height) / 2);
        frm_Principal.escritorio.add(ven);
        try {
            ven.toFront();
            ven.setSelected(true);
        } catch (Exception ex) {
        }
    }//GEN-LAST:event_btnConexionActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (new MensajeSistema().Salir()) {
            System.exit(0);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        this.limpiarPag2();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void txtHostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHostActionPerformed
        int valor = this.txtHost.verificarVacioConMsj();
        if (valor == 0) {
            this.txtPort.setNumero("3306");
            this.txtPort.grabFocus();
        } else if (valor == 1) {
            this.limpiarPag2();
        }
    }//GEN-LAST:event_txtHostActionPerformed

    private void txtPortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPortActionPerformed
        if (this.txtPort.getNumeroInt() <= 0) {
            int msn = MensajeSistema.MensajeOpciones(this, "No puede dejar vacio este campo...\nDesea Reintentar???",
                    new Object[]{"Si, Reintentar", "No, Cancelar"}, 0);
            if (msn == 0) {
                this.txtPort.setNumero("3306");
                this.txtPort.grabFocus();
            } else {
                this.limpiarPag2();
            }
        } else {
            this.txtUser.grabFocus();
        }
    }//GEN-LAST:event_txtPortActionPerformed

    private void txtUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserActionPerformed
        int valor = this.txtUser.verificarVacioConMsj();
        if (valor == 0) {
            this.txtPass.grabFocus();
        } else if (valor == 1) {
            this.limpiarPag2();
        }
    }//GEN-LAST:event_txtUserActionPerformed

    private void txtPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPassActionPerformed
        int valor = this.txtPass.verificarVacioConMsj();
        if (valor == 0) {
            this.txtBD.grabFocus();
        } else if (valor == 1) {
            this.limpiarPag2();
        }
    }//GEN-LAST:event_txtPassActionPerformed

    private void txtBDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBDActionPerformed
        int valor = this.txtBD.verificarVacioConMsj();
        if (valor == 0) {
            this.txtImpresora.grabFocus();
        } else if (valor == 1) {
            this.limpiarPag2();
        }
    }//GEN-LAST:event_txtBDActionPerformed

    private void txtImpresoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtImpresoraActionPerformed
        int valor = this.txtImpresora.verificarVacioConMsj();
        if (valor == 0) {
            this.cboDecoracion.grabFocus();
        } else if (valor == 1) {
            this.limpiarPag2();
        }
    }//GEN-LAST:event_txtImpresoraActionPerformed

    private void txtPass1_UserFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPass1_UserFocusGained
        this.textClave1.setVisible(true);
    }//GEN-LAST:event_txtPass1_UserFocusGained

    private void txtPass1_UserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPass1_UserActionPerformed
        int valor = txtPass1_User.verificarVacioConMsj();
        if (valor == 0) {
            if (this.txtPass1_User.verificarCantidadMinima()) {
                this.txtPass1_User.setEnabled(false);
                this.txtPass2_User.setEnabled(true);
                this.txtPass2_User.setSelectionStart(0);
                this.txtPass2_User.setSelectionEnd(this.txtPass2_User.getText().length());
                this.txtPass2_User.grabFocus();
            }
        } else if (valor == 1) {
            this.limpiarPag3();
        }
    }//GEN-LAST:event_txtPass1_UserActionPerformed

    private void txtPass2_UserFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPass2_UserFocusGained
        this.textClave2.setVisible(true);
    }//GEN-LAST:event_txtPass2_UserFocusGained

    private void txtPass2_UserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPass2_UserActionPerformed
        int valor = txtPass2_User.verificarVacioConMsj();
        if (valor == 0) {
            if (txtPass2_User.verificarCantidadMinima()) {
                if (this.txtPass1_User.getText().equals(this.txtPass2_User.getText())) {
                    this.btnGrabarUser.setEnabled(true);
                    this.textClave2.setVisible(false);
                    this.btnGrabarUser.grabFocus();
                } else {
                    int preg = MensajeSistema.Pregunta_YES_NO(this, "No coiciden las contraseñas...\nQuiere volver a intentar?...");
                    if (preg == MensajeSistema.YES_OPTION()) {
                        this.txtPass1_User.setText("");
                        this.txtPass2_User.setText("");
                        this.txtPass1_User.setEnabled(true);
                        this.txtPass1_User.grabFocus();
                    } else {
                        this.limpiarPag3();
                    }
                }
            }
        } else if (valor == 1) {
            this.limpiarPag3();
        }
    }//GEN-LAST:event_txtPass2_UserActionPerformed

    private void txtCod_PerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCod_PerfilActionPerformed
        if (this.txtCod_Perfil.verificarVacioSinMsj()) {
            String rs = this.getConexion.getDescripcion(this.txtCod_Perfil.getBdTabla(), this.txtCod_Perfil.getBdDescrip(),
                    new String[]{cod_empresa, this.txtCod_Perfil.getBdCodigo()},
                    new String[]{this.txtCod_Empresa.getText(), this.txtCod_Perfil.getText()});
            if (rs != null) {
                this.textNomPerfil.setText(rs);
                this.txtPass1_User.setEnabled(true);
                this.txtPass1_User.setSelectionEnd(this.txtPass1_User.getText().length());
                this.txtPass1_User.grabFocus();
            } else {
                MensajeSistema.ConsultaSQLVacio(this);
                this.txtCod_Perfil.setText("");
                this.textNomPerfil.setText("");
                this.txtCod_Perfil.grabFocus();
            }
        }
    }//GEN-LAST:event_txtCod_PerfilActionPerformed

    private void txtCod_PerfilKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCod_PerfilKeyPressed
        if (evt.getKeyCode() == ClaseTeclas.VK_F5()) {
            Buscar(this.txtCod_Perfil.getBdTabla(), true, false, this.txtCod_Perfil.getBdDescrip(), this.txtCod_Perfil.getBdDescrip(), this.txtCod_Perfil.getBdTitulo());
            this.txtCod_Perfil.requestFocus();
        }
    }//GEN-LAST:event_txtCod_PerfilKeyPressed

    private void txtNom_UserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNom_UserActionPerformed
        int valor = this.txtNom_User.verificarVacioConMsj();
        if (valor == 0) {
            this.txtCod_Perfil.setEnabled(true);
            this.txtCod_Perfil.grabFocus();
        } else if (valor == 1) {
            this.limpiarPag2();
        }
    }//GEN-LAST:event_txtNom_UserActionPerformed

    private void txtNom_UserKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNom_UserKeyTyped
        this.txtNom_User.CantidadLetras(evt, 25);
    }//GEN-LAST:event_txtNom_UserKeyTyped

    private void txtCod_EmpresaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCod_EmpresaKeyPressed
        if (evt.getKeyCode() == ClaseTeclas.VK_F5()) {
            Buscar(this.txtCod_Empresa.getBdTabla(), true, false, this.txtCod_Empresa.getBdCodigo(), this.txtCod_Empresa.getBdDescrip(), this.txtCod_Empresa.getBdTitulo());
            this.txtCod_Empresa.requestFocus();
        }
    }//GEN-LAST:event_txtCod_EmpresaKeyPressed

    private void txtCod_EmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCod_EmpresaActionPerformed
        int valor = this.txtCod_Empresa.verificarVacioConMsj();
        if (valor == 0) {
            String descri = getConexion.getDescripcion(this.txtCod_Empresa.getBdTabla(), this.txtCod_Empresa.getBdDescrip(),
                    new String[]{this.txtCod_Empresa.getBdCodigo()}, new String[]{this.txtCod_Empresa.getText()});
            if (descri != null) {
                this.textEmpresa.setText(descri);
                this.txtNom_User.grabFocus();
            } else {
                if (MensajeSistema.ConsultaSQLVacio()) {
                    this.txtCod_Empresa.setText("");
                    this.textEmpresa.setText("");
                    this.txtCod_Empresa.grabFocus();
                } else {
                    this.limpiarPag3();
                }
            }
        } else if (valor == 1) {
            this.limpiarPag3();
        }
    }//GEN-LAST:event_txtCod_EmpresaActionPerformed

    private void btnGrabarUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrabarUserActionPerformed
        this.GrabarUser();
    }//GEN-LAST:event_btnGrabarUserActionPerformed

    private void cboDecoracionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cboDecoracionFocusLost
        this.btnCrear.grabFocus();
    }//GEN-LAST:event_cboDecoracionFocusLost

    private void cboDecoracionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cboDecoracionKeyPressed
        if (evt.getKeyCode() == ClaseTeclas.VK_ENTER()) {
            this.cboDecoracion.transferFocus();
        }
    }//GEN-LAST:event_cboDecoracionKeyPressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.app.botones.btnCancelar btnCancelarUser;
    private javax.swing.JButton btnConexion;
    private javax.swing.JButton btnCrear;
    private com.app.botones.btnGrabar btnGrabarUser;
    private javax.swing.JButton btnLimpiar;
    private com.app.paleta.cbo cboDecoracion;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private com.app.paleta.JLabelFechaHora jLabelFechaHora1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanelTitulo;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel textClave1;
    private javax.swing.JLabel textClave2;
    private javax.swing.JLabel textEmpresa;
    private javax.swing.JLabel textNomPerfil;
    private javax.swing.JLabel textTitulo;
    private com.app.paleta.txtTexto txtBD;
    private com.app.paleta.txtCodigo txtCod_Empresa;
    private com.app.paleta.txtCodigo txtCod_Perfil;
    private com.app.paleta.txtTexto txtHost;
    private com.app.paleta.txtTexto txtImpresora;
    private com.app.paleta.txtTexto txtNom_User;
    private com.app.paleta.txtPassword txtPass;
    private com.app.paleta.txtPassword txtPass1_User;
    private com.app.paleta.txtPassword txtPass2_User;
    private com.app.paleta.txtNumeros txtPort;
    private com.app.paleta.txtTexto txtUser;
    // End of variables declaration//GEN-END:variables

    private void cargarCombo() {
        this.cboDecoracion.removeAllItems();
        String[] deco = {"AutumnSkin", "BusinessSkin", "BusinessBlueSteelSkin", "BusinessBlackSteelSkin",
            "ChallengerDeepSkin", "CremeSkin", "EmeraldDuskSkin", "FieldOfWheatSkin", "FindingNemoSkin",
            "GreenMagicSkin", "MagmaSkin", "MangoSkin", "MistAquaSkin", "MistSilverSkin", "ModerateSkin",
            "NebulaSkin", "OfficeBlue2007Skin", "OfficeSilver2007Skin", "RavenSkin", "SaharaSkin", "SubstanceSkin"};
        this.cboDecoracion.addItem(deco);
        this.cboDecoracion.setSelectedIndex(0);
    }

    private void limpiarPag2() {
        if (this.Archivo) {
            this.txtHost.setText(propiedades.getHost());
            this.txtPort.setText(propiedades.getPort());
            this.txtUser.setText(propiedades.getUser());
            this.txtPass.setText(ClaseEncriptacion.descifrarTexto(propiedades.getPass()));
            this.txtBD.setText(propiedades.getBD());
            this.txtImpresora.setText(propiedades.getImpresora());
            try {
                this.cboDecoracion.setSelecDescri(propiedades.getDecoracion().trim());
            } catch (Exception ex) {
                this.cboDecoracion.setSelectedIndex(0);
            }
        } else {
            this.txtHost.setText("");
            this.txtPort.setText("");
            this.txtUser.setText("");
            this.txtPass.setText("");
            this.txtBD.setText("");
            this.txtImpresora.setText("");
            this.cboDecoracion.removeAllItems();
        }
    }

    private void limpiarPag3() {
        ClaseCampos.SetTextNull(jPanel4);
        this.textEmpresa.setText("");
        this.textNomPerfil.setText("");
        this.textClave1.setVisible(false);
        this.textClave2.setVisible(false);
        this.btnGrabarUser.setEnabled(false);
        this.jTabbedPane1.setSelectedIndex(0);
    }

    private void crearArchiConfiguracion() {
        if (ClaseCampos.setValidate(jPanel3)) {
            MensajeSistema.MensajeVarios(this, "Existen campos que estan vacios...", MensajeSistema.ERROR_MESSAGE());
            this.txtHost.grabFocus();
        } else {
            if (this.Archivo) {
                propiedades.setHost(this.txtHost.getText().trim());
                propiedades.setPort(this.txtPort.getText().trim());
                propiedades.setUser(this.txtUser.getText().trim());
                propiedades.setPass(ClaseEncriptacion.cifrarTexto(this.txtPass.getText().trim()));
                propiedades.setBD(this.txtBD.getText().trim());
                propiedades.setImpresora(this.txtImpresora.getText().trim());
                propiedades.setDecoracion(this.cboDecoracion.getSelecDescri());
                MensajeSistema.MensajeVarios(this, "Archivo de Configuración Actualizado...\n\nSalga y vuelva abrir el programa...\n", MensajeSistema.INFORMATION_MESSAGE());
                this.jTabbedPane1.setSelectedIndex(0);
            } else {
                String texto = "host=" + ClaseEncriptacion.cifrarTexto(this.txtHost.getText().trim()) + "\n"
                        + "port=" + ClaseEncriptacion.cifrarTexto(this.txtPort.getText().trim()) + "\n"
                        + "user=" + ClaseEncriptacion.cifrarTexto(this.txtUser.getText().trim()) + "\n"
                        + "pass=" + ClaseEncriptacion.cifrarTexto(this.txtPass.getText().trim()) + "\n"
                        + "bd=" + ClaseEncriptacion.cifrarTexto(this.txtBD.getText().trim()) + "\n"
                        + "impresora=" + ClaseEncriptacion.cifrarTexto(this.txtImpresora.getText().trim()) + "\n"
                        + "decoracion=" + ClaseEncriptacion.cifrarTexto(this.cboDecoracion.getSelecDescri());
                try {
                    ClaseTextoIO.escribirArchivoNuevo("configuracion.properties", texto);
                    MensajeSistema.MensajeVarios(this, "Archivo de Configuración creado...\n\nSalga y vuelva abrir el programa...\n", MensajeSistema.INFORMATION_MESSAGE());
                    this.jTabbedPane1.setSelectedIndex(0);
                } catch (IOException ex) {
                    MensajeSistema.setIOException(this, "Se produjo un error al Crear el archivo de configuración", ex);
                }
            }
        }
    }

    private void GrabarUser() {
        if (MensajeSistema.Guardar(this)) {
            int vCod = getConexion.getMAX(tablaConsutada, idConsultada,
                    new String[]{cod_empresa},
                    new String[]{this.txtCod_Empresa.getText()});
            this.getConexion.insertar(tablaConsutada,
                    new String[]{cod_empresa, idConsultada, this.txtCod_Perfil.getBdDescrip(), "clave", this.txtCod_Perfil.getBdCodigo()},
                    new String[]{this.txtCod_Empresa.getText(), String.valueOf(vCod), this.txtNom_User.getText(), "PASSWORD(" + this.txtPass1_User.getText() + ")", this.txtCod_Perfil.getText()});
        }
        this.limpiarPag3();
    }
}
