package com.app.form.Especiales;

import com.app.clases.ClaseBotones;
import com.app.clases.ClaseTableModel;
import com.app.clases.ClaseTeclas;
import com.app.config.ConexionBD;
import com.app.config.Configuracion;
import com.app.config.ConsultaSQL;
import com.app.config.MensajeSistema;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author diego
 */
public class Mantenimiento_Permisos extends frm_Padre {

    private final DefaultTableModel ModeloPermisos, ModeloMenus;
    private final String[] vacio = {};
    private String Cod_Sucursal, Cod_Perfil;
    private boolean v_autorizado = false, v_agregar = false, v_modificar = false;
    private boolean v_borrar = false, v_listar = false;
    private boolean v_todos = false;

    public Mantenimiento_Permisos(ConexionBD conexion) {
        initComponents();
        this.setName("Mant_Permisos");
        this.getConexion = conexion;
        this.getConexion.getConexion();
        ClaseBotones.botonesABMKeyPressed(btnNuevo, btnModificar, btnBorrar, btnListar, btnGrabar, btnCancelar, btnSalir);
        ClaseTableModel.setAncho(jTablePermisos, new int[]{0, 1, 2, 3, 4, 5, 6}, new int[]{50, 300, 30, 30, 30, 30, 30});
        this.ModeloPermisos = (DefaultTableModel) jTablePermisos.getModel();
        this.ModeloMenus = (DefaultTableModel) jTableMenus.getModel();
        ClaseTableModel.setAncho(jTableMenus, new int[]{0, 1, 2}, new int[]{50, 200, 30});
        this.Inicializar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pnlTitulo = new javax.swing.JPanel();
        textTitulo = new javax.swing.JLabel();
        jPanelPermisos = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePermisos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButtonAutorizado = new javax.swing.JButton();
        jButtonAgregar = new javax.swing.JButton();
        jButtonModificar = new javax.swing.JButton();
        jButtonBorrar = new javax.swing.JButton();
        jButtonListar = new javax.swing.JButton();
        jPanelDatos = new javax.swing.JPanel();
        btnNuevo = new com.app.botones.btnNuevo();
        btnModificar = new com.app.botones.btnModificar();
        btnBorrar = new com.app.botones.btnBorrar();
        btnGrabar = new com.app.botones.btnGrabar();
        btnCancelar = new com.app.botones.btnCancelar();
        btnListar = new com.app.botones.btnListar();
        btnSalir = new com.app.botones.btnSalir();
        jLabel3 = new javax.swing.JLabel();
        jComboSucursal = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jComboPerfil = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableMenus = new javax.swing.JTable();
        jButtonTodos = new javax.swing.JButton();
        jButtonPasar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        pnlTitulo.setBackground(new java.awt.Color(204, 204, 204));
        pnlTitulo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlTitulo.setMaximumSize(new java.awt.Dimension(486, 60));
        pnlTitulo.setMinimumSize(new java.awt.Dimension(486, 60));
        pnlTitulo.setName(""); // NOI18N

        textTitulo.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        textTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textTitulo.setText("Mantenimiento de Permisos...");

        javax.swing.GroupLayout pnlTituloLayout = new javax.swing.GroupLayout(pnlTitulo);
        pnlTitulo.setLayout(pnlTituloLayout);
        pnlTituloLayout.setHorizontalGroup(
            pnlTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlTituloLayout.setVerticalGroup(
            pnlTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanelPermisos.setBorder(javax.swing.BorderFactory.createTitledBorder("Permisos"));

        jTablePermisos.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jTablePermisos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Menú", "Autorizado", "Agregar", "Modificar", "Borrar", "Listar"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTablePermisos);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Todos:");

        jButtonAutorizado.setText("Autorizado");
        jButtonAutorizado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAutorizadoActionPerformed(evt);
            }
        });

        jButtonAgregar.setText("Agregar");
        jButtonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarActionPerformed(evt);
            }
        });

        jButtonModificar.setText("Modificar");
        jButtonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarActionPerformed(evt);
            }
        });

        jButtonBorrar.setText("Borrar");
        jButtonBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBorrarActionPerformed(evt);
            }
        });

        jButtonListar.setText("Listar");
        jButtonListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelPermisosLayout = new javax.swing.GroupLayout(jPanelPermisos);
        jPanelPermisos.setLayout(jPanelPermisosLayout);
        jPanelPermisosLayout.setHorizontalGroup(
            jPanelPermisosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPermisosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPermisosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanelPermisosLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonAutorizado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonAgregar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonModificar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonBorrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonListar, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanelPermisosLayout.setVerticalGroup(
            jPanelPermisosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPermisosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelPermisosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jButtonAutorizado)
                    .addComponent(jButtonAgregar)
                    .addComponent(jButtonModificar)
                    .addComponent(jButtonBorrar)
                    .addComponent(jButtonListar)))
        );

        jPanelDatos.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });

        btnGrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrabarActionPerformed(evt);
            }
        });

        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarActionPerformed(evt);
            }
        });

        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelDatosLayout = new javax.swing.GroupLayout(jPanelDatos);
        jPanelDatos.setLayout(jPanelDatosLayout);
        jPanelDatosLayout.setHorizontalGroup(
            jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGrabar, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnListar, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelDatosLayout.setVerticalGroup(
            jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGrabar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnListar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Sucursales...");

        jComboSucursal.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jComboSucursalFocusGained(evt);
            }
        });
        jComboSucursal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jComboSucursalKeyPressed(evt);
            }
        });

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Perfiles...");

        jComboPerfil.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jComboPerfilFocusGained(evt);
            }
        });
        jComboPerfil.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jComboPerfilKeyPressed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Menús"));

        jTableMenus.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jTableMenus.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Descripción", "Marcar"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTableMenus);

        jButtonTodos.setText("Todos");
        jButtonTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTodosActionPerformed(evt);
            }
        });

        jButtonPasar.setText("<< Pasar");
        jButtonPasar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPasarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 418, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jButtonPasar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonTodos)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 445, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonTodos)
                    .addComponent(jButtonPasar))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(pnlTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanelDatos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanelPermisos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboSucursal, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jComboSucursal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jComboPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelPermisos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        this.Agregar();
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        this.Editar('M');
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        this.Editar('E');
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void btnGrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrabarActionPerformed
        this.Grabar();
    }//GEN-LAST:event_btnGrabarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.Cancelar();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActionPerformed
        this.Listar();
    }//GEN-LAST:event_btnListarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.Salir(this);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void jComboSucursalKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jComboSucursalKeyPressed
        if (evt.getKeyCode() == ClaseTeclas.VK_ENTER()) {
            if (this.jComboSucursal.getSelectedIndex() == 0) {
                MensajeSistema.MensajeVarios(this, "Seleccione un registro y vuelva intentar...", MensajeSistema.ERROR_MESSAGE());
                this.jComboSucursal.grabFocus();
            } else {
                claseSucursal suc = (claseSucursal) this.jComboSucursal.getSelectedItem();
                this.Cod_Sucursal = suc.getCodigo();
                if (this.CargarPerfil()) {
                    this.jComboPerfil.setEnabled(true);
                    this.jComboPerfil.grabFocus();
                } else {
                    this.Inicializar();
                }
            }
        }
    }//GEN-LAST:event_jComboSucursalKeyPressed

    private void jComboPerfilKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jComboPerfilKeyPressed
        if (evt.getKeyCode() == ClaseTeclas.VK_ENTER()) {
            if (this.jComboPerfil.getSelectedIndex() == 0) {
                MensajeSistema.MensajeVarios(this, "Seleccione un registro y vuelva intentar...", MensajeSistema.ERROR_MESSAGE());
                this.jComboPerfil.grabFocus();
            } else {
                clasePerfiles per = (clasePerfiles) this.jComboPerfil.getSelectedItem();
                this.Cod_Perfil = per.getCodigo();
                boolean existe = true;
                if (this.CargarPermisos()) {
                    if (operacion == 'A') {
                        MensajeSistema.MensajeVarios(this, "Ya existen permisos para el parametro ingresado...", MensajeSistema.INFORMATION_MESSAGE());
                        operacion = 'M';
                    }
                } else {
                    if (operacion == 'M' || operacion == 'E') {
                        MensajeSistema.ConsultaSQLVacio(this);
                        existe = false;
                    }
                }

                this.CargarMenus();
                if (existe) {
                    if (operacion == 'E') {
                        this.Borrar();
                    } else {
                        this.jButtonAutorizado.setEnabled(true);
                        this.jButtonAgregar.setEnabled(true);
                        this.jButtonModificar.setEnabled(true);
                        this.jButtonBorrar.setEnabled(true);
                        this.jButtonListar.setEnabled(true);
                        this.jButtonPasar.setEnabled(true);
                        this.jButtonTodos.setEnabled(true);
                        this.btnGrabar.setEnabled(true);
                        this.jButtonAutorizado.grabFocus();
                    }
                } else {
                    this.Inicializar();
                }
            }
        }
    }//GEN-LAST:event_jComboPerfilKeyPressed

    private void jComboSucursalFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jComboSucursalFocusGained
        this.jComboSucursal.setPopupVisible(true);
    }//GEN-LAST:event_jComboSucursalFocusGained

    private void jComboPerfilFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jComboPerfilFocusGained
        this.jComboPerfil.setPopupVisible(true);
    }//GEN-LAST:event_jComboPerfilFocusGained

    private void jButtonAutorizadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAutorizadoActionPerformed
        for (int i = 0; i < ModeloPermisos.getRowCount(); i++) {
            this.ModeloPermisos.setValueAt(!v_autorizado, i, 2);
        }
        v_autorizado = !v_autorizado;
    }//GEN-LAST:event_jButtonAutorizadoActionPerformed

    private void jButtonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarActionPerformed
        for (int i = 0; i < ModeloPermisos.getRowCount(); i++) {
            this.ModeloPermisos.setValueAt(!v_agregar, i, 3);
        }
        v_agregar = !v_agregar;
    }//GEN-LAST:event_jButtonAgregarActionPerformed

    private void jButtonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarActionPerformed
        for (int i = 0; i < ModeloPermisos.getRowCount(); i++) {
            this.ModeloPermisos.setValueAt(!v_modificar, i, 4);
        }
        v_modificar = !v_modificar;
    }//GEN-LAST:event_jButtonModificarActionPerformed

    private void jButtonBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBorrarActionPerformed
        for (int i = 0; i < ModeloPermisos.getRowCount(); i++) {
            this.ModeloPermisos.setValueAt(!v_borrar, i, 5);
        }
        v_borrar = !v_borrar;
    }//GEN-LAST:event_jButtonBorrarActionPerformed

    private void jButtonTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTodosActionPerformed
        for (int i = 0; i < ModeloMenus.getRowCount(); i++) {
            this.ModeloMenus.setValueAt(!v_todos, i, 2);
        }
        v_todos = !v_todos;
    }//GEN-LAST:event_jButtonTodosActionPerformed

    private void jButtonListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListarActionPerformed
        for (int i = 0; i < ModeloPermisos.getRowCount(); i++) {
            this.ModeloPermisos.setValueAt(!v_listar, i, 6);
        }
        v_listar = !v_listar;
    }//GEN-LAST:event_jButtonListarActionPerformed

    private void jButtonPasarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPasarActionPerformed
        this.pasarMenus();
    }//GEN-LAST:event_jButtonPasarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.app.botones.btnBorrar btnBorrar;
    private com.app.botones.btnCancelar btnCancelar;
    private com.app.botones.btnGrabar btnGrabar;
    private com.app.botones.btnListar btnListar;
    private com.app.botones.btnModificar btnModificar;
    private com.app.botones.btnNuevo btnNuevo;
    private com.app.botones.btnSalir btnSalir;
    private javax.swing.JButton jButtonAgregar;
    private javax.swing.JButton jButtonAutorizado;
    private javax.swing.JButton jButtonBorrar;
    private javax.swing.JButton jButtonListar;
    private javax.swing.JButton jButtonModificar;
    private javax.swing.JButton jButtonPasar;
    private javax.swing.JButton jButtonTodos;
    private javax.swing.JComboBox jComboPerfil;
    private javax.swing.JComboBox jComboSucursal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelDatos;
    private javax.swing.JPanel jPanelPermisos;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableMenus;
    private javax.swing.JTable jTablePermisos;
    private javax.swing.JPanel pnlTitulo;
    private javax.swing.JLabel textTitulo;
    // End of variables declaration//GEN-END:variables

    private void Inicializar() {
        this.btnNuevo.setEnabled(true);
        this.btnModificar.setEnabled(true);
        this.btnBorrar.setEnabled(true);
        this.btnListar.setEnabled(true);
        this.btnGrabar.setEnabled(false);
        this.btnCancelar.setEnabled(false);
        this.btnSalir.setEnabled(true);
        this.ModeloPermisos.setRowCount(0);
        this.ModeloMenus.setRowCount(0);
        this.jComboSucursal.removeAllItems();
        this.jComboPerfil.removeAllItems();
        this.jComboSucursal.setEnabled(false);
        this.jComboPerfil.setEnabled(false);
        ClaseBotones.modoEdicionABM(btnNuevo, btnModificar, btnBorrar, btnListar, btnGrabar, btnCancelar, btnSalir, true);
        this.jButtonAutorizado.setEnabled(false);
        this.jButtonAgregar.setEnabled(false);
        this.jButtonModificar.setEnabled(false);
        this.jButtonBorrar.setEnabled(false);
        this.jButtonListar.setEnabled(false);
        this.jButtonPasar.setEnabled(false);
        this.jButtonTodos.setEnabled(false);
        this.operacion = 'x';
        this.Cod_Sucursal = "";
        this.Cod_Perfil = "";
        this.btnNuevo.grabFocus();
    }

    private void Grabar() {
        if (MensajeSistema.Guardar(this)) {
            int cantidadRow = this.ModeloPermisos.getRowCount();
            for (int i = cantidadRow - 1; i >= 0; i--) {
                if ("false".equals(this.ModeloPermisos.getValueAt(i, 2).toString())) {
                    ClaseTableModel.removeRowjTable(jTablePermisos, i);
                }
            }
            cantidadRow = this.ModeloPermisos.getRowCount();
            this.getConexion.Begin();
            boolean exito = true;
            if (operacion == 'M') {
                exito = this.getConexion.eliminar("Acc_Principal",
                        new String[]{cod_empresa, cod_sucursal, "Perf_Codigo"},
                        new String[]{Configuracion.getCOD_EMPRESA(), this.Cod_Sucursal, this.Cod_Perfil});
            }
            if (exito) {
                String[][] registros = new String[cantidadRow][9];
//                for (int i = 0; i < cantidadRow; i++) {
//                    exito = this.getConexion.insertar("acc_principal",
//                            new String[]{"cod_empresa", "cod_sucursal", "cod_perfil", "cod_menu",
//                                "autorizado_ok", "agrega_ok", "modifica_ok", "borra_ok", "listar_ok"},
//                            new String[]{Configuracion.getCOD_EMPRESA(), this.Cod_Sucursal, this.Cod_Perfil,
//                                this.ModeloPermisos.getValueAt(i, 0).toString(),
//                                "true".equals(this.ModeloPermisos.getValueAt(i, 2).toString()) ? "1" : "0",
//                                "true".equals(this.ModeloPermisos.getValueAt(i, 3).toString()) ? "1" : "0",
//                                "true".equals(this.ModeloPermisos.getValueAt(i, 4).toString()) ? "1" : "0",
//                                "true".equals(this.ModeloPermisos.getValueAt(i, 5).toString()) ? "1" : "0",
//                                "true".equals(this.ModeloPermisos.getValueAt(i, 6).toString()) ? "1" : "0"});
//                    if (exito == false) {
//                        this.getConexion.RollBack();
//                        break;
//                    }
//                }
                for (int i = 0; i < cantidadRow; i++) {
                    registros[i][0] = Configuracion.getCOD_EMPRESA();
                    registros[i][1] = this.Cod_Sucursal;
                    registros[i][2] = this.Cod_Perfil;
                    registros[i][3] = this.ModeloPermisos.getValueAt(i, 0).toString();
                    registros[i][4] = "true".equals(this.ModeloPermisos.getValueAt(i, 2).toString()) ? "1" : "0";
                    registros[i][5] = "true".equals(this.ModeloPermisos.getValueAt(i, 3).toString()) ? "1" : "0";
                    registros[i][6] = "true".equals(this.ModeloPermisos.getValueAt(i, 4).toString()) ? "1" : "0";
                    registros[i][7] = "true".equals(this.ModeloPermisos.getValueAt(i, 5).toString()) ? "1" : "0";
                    registros[i][8] = "true".equals(this.ModeloPermisos.getValueAt(i, 6).toString()) ? "1" : "0";

                }
                if (this.getConexion.insertar("Acc_Principal",
                        new String[]{cod_empresa, cod_sucursal, "Perf_Codigo", "Men_Codigo",
                            "autorizado_ok", "agrega_ok", "modifica_ok", "borra_ok", "listar_ok"},
                        registros, cantidadRow, 9) == false) {
                    this.getConexion.RollBack();
                }

            }
            this.getConexion.Commit();
        }
        this.Inicializar();
    }

    private void Agregar() {
        ClaseBotones.modoEdicionABM(btnNuevo, btnModificar, btnBorrar, btnListar, btnGrabar, btnCancelar, btnSalir, false);
        this.btnGrabar.setEnabled(false);
        if (this.CargarSucursal()) {
            this.operacion = 'A';
            this.jComboSucursal.setEnabled(true);
            this.jComboSucursal.grabFocus();
        } else {
            this.Inicializar();
        }
    }

    private void Borrar() {
        if (MensajeSistema.Eliminar(this)) {
            this.getConexion.eliminar("Acc_Principal",
                    new String[]{cod_empresa, cod_sucursal, "Perf_Codigo"},
                    new String[]{Configuracion.getCOD_EMPRESA(), this.Cod_Sucursal, this.Cod_Perfil});
        }
        this.Inicializar();
    }

    private void Editar(char c) {
        this.operacion = c;
        this.jComboSucursal.setEnabled(true);
        ClaseBotones.modoEdicionABM(btnNuevo, btnModificar, btnBorrar, btnListar, btnGrabar, btnCancelar, btnSalir, false);
        this.btnGrabar.setEnabled(false);
        if (this.CargarSucursal()) {
            this.jComboSucursal.grabFocus();
        } else {
            this.Inicializar();
        }
    }

    private void Cancelar() {
        if (MensajeSistema.Cancelar(this)) {
            this.Inicializar();
        }
    }

    private void Listar() {

    }

    private boolean CargarSucursal() {
        jComboSucursal.removeAllItems();
        ArrayList<claseSucursal> lista = ObtenerListaSucursal();
        if (lista.size() > 0) {
            jComboSucursal.addItem("Seleccione...");
            for (claseSucursal lista1 : lista) {
                jComboSucursal.addItem(new claseSucursal(lista1.getCodigo(), lista1.getDescripcion()));
            }
            return true;
        }
        return false;
    }

    private boolean CargarPerfil() {
        jComboPerfil.removeAllItems();
        ArrayList<clasePerfiles> lista = ObtenerListaPerfil();
        if (lista.size() > 0) {
            jComboPerfil.addItem("Seleccione...");
            for (clasePerfiles lista1 : lista) {
                jComboPerfil.addItem(new clasePerfiles(lista1.getCodigo(), lista1.getDescripcion()));
            }
            return true;
        }
        return false;
    }

    private boolean CargarPermisos() {        
        this.ModeloPermisos.setRowCount(0);
        String consulta = ConsultaSQL.getSelect("vst_Acc_Principal",
                new String[]{"Men_Codigo", "Men_Descrip", "autorizado_ok", "agrega_ok", "modifica_ok", "borra_ok", "listar_ok"},
                vacio,
                new String[]{cod_empresa, cod_sucursal, "Perf_Codigo"},
                new String[]{Configuracion.getCOD_EMPRESA(), this.Cod_Sucursal, this.Cod_Perfil},
                new String[]{"Men_Codigo"});
        String[][] rs = this.getConexion.getDescripcionesRow(consulta);
        if (rs[0][0] != null) {
            Object[] datos = new Object[7];
            for (String[] resu : rs) {
                datos[0] = resu[0];
                datos[1] = resu[1];
                datos[2] = "1".equals(resu[2]);
                datos[3] = "1".equals(resu[3]);
                datos[4] = "1".equals(resu[4]);
                datos[5] = "1".equals(resu[5]);
                datos[6] = "1".equals(resu[6]);
                ModeloPermisos.addRow(datos);
            }
            return true;
        }
        return false;
    }

    private boolean CargarMenus() {
        this.ModeloMenus.setRowCount(0);
        String consulta = "SELECT Men_Codigo,Men_Descrip FROM Acc_Menus ";
        consulta += "WHERE " + cod_empresa + "='" + Configuracion.getCOD_EMPRESA() + "' and Men_Codigo NOT IN (SELECT Men_Codigo ";
        consulta += "FROM Acc_Principal WHERE " + cod_empresa + "='" + Configuracion.getCOD_EMPRESA() + "'";
        consulta += " AND " + cod_sucursal + "='" + this.Cod_Sucursal + "' AND Perf_Codigo='" + this.Cod_Perfil + "')";
        String[][] rs = this.getConexion.getDescripcionesRow(consulta);
        if (rs[0][0] != null) {
            Object[] datos = new Object[3];
            for (String[] resu : rs) {
                datos[0] = resu[0];
                datos[1] = resu[1];
                datos[2] = false;
                ModeloMenus.addRow(datos);
            }
            return true;
        }
        return false;
    }

    private void pasarMenus() {
        int cantidadRow = this.ModeloMenus.getRowCount();
        for (int i = 0; i < cantidadRow; i++) {
            if (this.jTableMenus.getValueAt(i, 2).toString().equals("true")) {
                Object[] datos = new Object[7];
                datos[0] = this.ModeloMenus.getValueAt(i, 0);
                datos[1] = this.ModeloMenus.getValueAt(i, 1);
                datos[2] = false;
                datos[3] = false;
                datos[4] = false;
                datos[5] = false;
                datos[6] = false;
                ModeloPermisos.addRow(datos);
                ModeloMenus.setValueAt("", i, 0);
            }
        }
        for (int i = cantidadRow - 1; i >= 0; i--) {
            if ("".equals(ModeloMenus.getValueAt(i, 0))) {
                ClaseTableModel.removeRowjTable(jTableMenus, i);
            }
        }
    }

    private ArrayList ObtenerListaSucursal() {
        ArrayList<claseSucursal> lista = new ArrayList<>();
        String[][] rs = getConexion.getDescripcionesRow("Adm_Sucursales",
                new String[]{"Suc_Codigo", "denominacion"},
                new String[]{cod_empresa},
                new String[]{Configuracion.getCOD_EMPRESA()});
        if (rs[0][0] != null) {
            for (String[] resu : rs) {
                claseSucursal combo = new claseSucursal(resu[0], resu[1]);
                lista.add(combo);
            }
        }
        return lista;
    }

    private ArrayList ObtenerListaPerfil() {
        ArrayList<clasePerfiles> lista = new ArrayList<>();
        String[][] rs = getConexion.getDescripcionesRow("Acc_Perfiles",
                new String[]{"Perf_Codigo", "Perf_Descrip"},
                new String[]{cod_empresa},
                new String[]{Configuracion.getCOD_EMPRESA()});
        if (rs[0][0] != null) {
            for (String[] resu : rs) {
                clasePerfiles combo = new clasePerfiles(resu[0], resu[1]);
                lista.add(combo);
            }
        }
        return lista;
    }

    private class claseSucursal {

        private String Codigo;
        private String Descripcion;

        public claseSucursal(String codigo, String descripcion) {
            this.Codigo = codigo;
            this.Descripcion = descripcion;
        }

        public String getDescripcion() {
            return Descripcion;
        }

        public void setDescripcion(String descripcion) {
            this.Descripcion = descripcion;
        }

        public String getCodigo() {
            return Codigo;
        }

        public void setCodigo(String codigo) {
            this.Codigo = codigo;
        }

        @Override
        public String toString() {
            return Codigo + " - " + Descripcion;
        }
    }

    private class clasePerfiles {

        private String Codigo;
        private String Descripcion;

        public clasePerfiles(String codigo, String descripcion) {
            this.Codigo = codigo;
            this.Descripcion = descripcion;
        }

        public String getDescripcion() {
            return Descripcion;
        }

        public void setDescripcion(String descripcion) {
            this.Descripcion = descripcion;
        }

        public String getCodigo() {
            return Codigo;
        }

        public void setCodigo(String codigo) {
            this.Codigo = codigo;
        }

        @Override
        public String toString() {
            return Codigo + " - " + Descripcion;
        }
    }
}
