package com.app.form;

import com.app.clases.ClaseBotones;
import com.app.clases.ClaseCampos;
import com.app.clases.ClaseTeclas;
import com.app.clases.ClaseUtilidades;
import com.app.config.Configuracion;
import com.app.config.ConsultaSQL;
import com.app.config.MensajeSistema;
import com.app.form.Especiales.frm_Padre;
import com.app.form.Especiales.frm_Padre.Metodos;
import static com.app.form.Especiales.frm_Padre.cod_empresa;

/**
 *
 * @author Diego
 */
public final class Contactos extends frm_Padre implements Metodos {

    public Contactos(int cod_ventana) {
        initComponents();
        this.setName("contactos");
        this.textTitulo.setText("Mantenimiento de Contactos...");
        this.tablaConsutada = "mant_contactos";
        this.UsarEmpresa = true;
        this.UsarSucursal = false;
        this.idConsultada = "Cont_Codigo";
        this.descripcionConsultada = "razon_social";
        this.tituloVentanaActual = "Contactos";
        this.getPermisos(cod_ventana);
        this.txtRazonSocial.setEnMayuscula(true);
        this.txtCINumero.setFormatear(false);
        ClaseBotones.botonesABMKeyPressed(btnNuevo, btnModificar, btnBorrar, btnGrabar, btnCancelar, btnSalir);

        this.txtCod_Nacionalidad.setBdTabla("Ref_Nacionalidades");
        this.txtCod_Nacionalidad.setBdCodigo("Nac_Codigo");
        this.txtCod_Nacionalidad.setBdDescrip("Nac_Descrip");
        this.txtCod_Nacionalidad.setBdTitulo("Nacionalidades");

        this.txtCod_Ciudad.setBdTabla("ref_ciudades");
        this.txtCod_Ciudad.setBdCodigo("Ciu_Codigo");
        this.txtCod_Ciudad.setBdDescrip("Ciu_Descrip");
        this.txtCod_Ciudad.setBdTitulo("Ciudades");
        Inicializar();
        this.btnNuevo.transferFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanelTitulo = new javax.swing.JPanel();
        textTitulo = new javax.swing.JLabel();
        jTab = new javax.swing.JTabbedPane();
        pnlMantenimiento = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtCod_Contacto = new com.app.paleta.txtCodigo();
        jLabel2 = new javax.swing.JLabel();
        txtCINumero = new com.app.paleta.txtNumeros();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtRazonSocial = new com.app.paleta.txtTexto();
        jLabel5 = new javax.swing.JLabel();
        txtTelefono = new com.app.paleta.txtTelefono();
        jLabel6 = new javax.swing.JLabel();
        txtCelular = new com.app.paleta.txtCelular();
        jLabel7 = new javax.swing.JLabel();
        txtTelefax1 = new com.app.paleta.txtTelefono();
        jLabel8 = new javax.swing.JLabel();
        txtTelefax2 = new com.app.paleta.txtTelefono();
        jLabel9 = new javax.swing.JLabel();
        txtDireccion = new com.app.paleta.txtTexto();
        jLabel10 = new javax.swing.JLabel();
        txtEmail = new com.app.paleta.txtTexto();
        jLabel12 = new javax.swing.JLabel();
        txtCod_Nacionalidad = new com.app.paleta.txtCodigo();
        textNom_Nacionalidad = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtCod_Ciudad = new com.app.paleta.txtCodigo();
        textNom_Ciudad = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        cboEstado = new javax.swing.JComboBox();
        jLabel17 = new javax.swing.JLabel();
        cboACredito = new javax.swing.JComboBox();
        jLabel20 = new javax.swing.JLabel();
        cboRetentor = new javax.swing.JComboBox();
        txtRuc = new com.app.paleta.txtNumeros();
        pnlVentas = new javax.swing.JPanel();
        textTitulo1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbltablaVenta = new com.app.paleta.tbl();
        pnlCompras = new javax.swing.JPanel();
        textTitulo2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbltablaCompra = new com.app.paleta.tbl();
        jPanelBotones = new javax.swing.JPanel();
        btnImagen1 = new com.app.botones.btnImagen();
        btnNuevo = new com.app.botones.btnNuevo();
        btnModificar = new com.app.botones.btnEditar();
        btnBorrar = new com.app.botones.btnBorrar();
        btnGrabar = new com.app.botones.btnGrabar();
        btnCancelar = new com.app.botones.btnCancelar();
        btnSalir = new com.app.botones.btnSalir();

        jPanelTitulo.setBackground(new java.awt.Color(204, 204, 204));
        jPanelTitulo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelTitulo.setMaximumSize(new java.awt.Dimension(486, 60));
        jPanelTitulo.setMinimumSize(new java.awt.Dimension(486, 60));
        jPanelTitulo.setName(""); // NOI18N

        textTitulo.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        textTitulo.setText("TITULO...");

        javax.swing.GroupLayout jPanelTituloLayout = new javax.swing.GroupLayout(jPanelTitulo);
        jPanelTitulo.setLayout(jPanelTituloLayout);
        jPanelTituloLayout.setHorizontalGroup(
            jPanelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelTituloLayout.setVerticalGroup(
            jPanelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlMantenimiento.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Código:");

        txtCod_Contacto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCod_ContactoActionPerformed(evt);
            }
        });
        txtCod_Contacto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCod_ContactoKeyPressed(evt);
            }
        });

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Nro CI.:");

        txtCINumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCINumeroActionPerformed(evt);
            }
        });

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("RUC:");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Razón Social:");

        txtRazonSocial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRazonSocialActionPerformed(evt);
            }
        });

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Teléfono:");

        txtTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefonoActionPerformed(evt);
            }
        });

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Celular:");

        txtCelular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCelularActionPerformed(evt);
            }
        });

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Teléfax 1:");

        txtTelefax1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefax1ActionPerformed(evt);
            }
        });

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Teléfax 2:");

        txtTelefax2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefax2ActionPerformed(evt);
            }
        });

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Direción:");

        txtDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDireccionActionPerformed(evt);
            }
        });

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("E-mail:");

        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("Nacionalidad:");

        txtCod_Nacionalidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCod_NacionalidadActionPerformed(evt);
            }
        });
        txtCod_Nacionalidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCod_NacionalidadKeyPressed(evt);
            }
        });

        textNom_Nacionalidad.setText("jLabel13");

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel15.setText("Ciudad:");

        txtCod_Ciudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCod_CiudadActionPerformed(evt);
            }
        });
        txtCod_Ciudad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCod_CiudadKeyPressed(evt);
            }
        });

        textNom_Ciudad.setText("jLabel13");

        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel16.setText("Estado:");

        cboEstado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione...", "ACTIVO", "INACTIVO" }));
        cboEstado.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cboEstadoFocusGained(evt);
            }
        });
        cboEstado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cboEstadoKeyPressed(evt);
            }
        });

        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel17.setText("a Crédito:");

        cboACredito.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione...", "SI", "NO" }));
        cboACredito.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cboACreditoFocusGained(evt);
            }
        });
        cboACredito.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cboACreditoKeyPressed(evt);
            }
        });

        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel20.setText("Retentor:");

        cboRetentor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione...", "SI", "NO" }));
        cboRetentor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cboRetentorFocusGained(evt);
            }
        });
        cboRetentor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cboRetentorKeyPressed(evt);
            }
        });

        txtRuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRucActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlMantenimientoLayout = new javax.swing.GroupLayout(pnlMantenimiento);
        pnlMantenimiento.setLayout(pnlMantenimientoLayout);
        pnlMantenimientoLayout.setHorizontalGroup(
            pnlMantenimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMantenimientoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMantenimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMantenimientoLayout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtRazonSocial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlMantenimientoLayout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDireccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMantenimientoLayout.createSequentialGroup()
                        .addGroup(pnlMantenimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlMantenimientoLayout.createSequentialGroup()
                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cboEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cboACredito, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(pnlMantenimientoLayout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(81, 81, 81)))
                        .addComponent(cboRetentor, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(167, 167, 167))
                    .addGroup(pnlMantenimientoLayout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCod_Nacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textNom_Nacionalidad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCod_Ciudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textNom_Ciudad, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlMantenimientoLayout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTelefax1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTelefax2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlMantenimientoLayout.createSequentialGroup()
                        .addGroup(pnlMantenimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pnlMantenimientoLayout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCod_Contacto, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlMantenimientoLayout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCINumero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtRuc, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlMantenimientoLayout.setVerticalGroup(
            pnlMantenimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMantenimientoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMantenimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCod_Contacto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlMantenimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCINumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtRuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlMantenimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtRazonSocial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlMantenimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(txtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelefax1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelefax2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlMantenimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlMantenimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlMantenimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtCod_Nacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textNom_Nacionalidad)
                    .addComponent(jLabel15)
                    .addComponent(txtCod_Ciudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textNom_Ciudad))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlMantenimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(cboEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(cboACredito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20)
                    .addComponent(cboRetentor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jTab.addTab("Mantenimiento", pnlMantenimiento);

        pnlVentas.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        textTitulo1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        textTitulo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textTitulo1.setText("SALDOS Y TOTALES EN VENTAS");

        tbltablaVenta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Moneda", "Saldo Anterior", "Tot. Contado", "Tot. Crédito", "Tot. Cobros", "Tot. Int. Gen.", "Saldo Actual"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tbltablaVenta);

        javax.swing.GroupLayout pnlVentasLayout = new javax.swing.GroupLayout(pnlVentas);
        pnlVentas.setLayout(pnlVentasLayout);
        pnlVentasLayout.setHorizontalGroup(
            pnlVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlVentasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textTitulo1, javax.swing.GroupLayout.DEFAULT_SIZE, 738, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        pnlVentasLayout.setVerticalGroup(
            pnlVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlVentasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textTitulo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTab.addTab("Ventas", pnlVentas);

        pnlCompras.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        textTitulo2.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        textTitulo2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textTitulo2.setText("SALDOS Y TOTALES EN COMPRAS");

        tbltablaCompra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Moneda", "Saldo Anterior", "Tot. Contado", "Tot. Crédito", "Tot. Pagos", "Tot. Int. Gen.", "Saldo Actual"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tbltablaCompra);

        javax.swing.GroupLayout pnlComprasLayout = new javax.swing.GroupLayout(pnlCompras);
        pnlCompras.setLayout(pnlComprasLayout);
        pnlComprasLayout.setHorizontalGroup(
            pnlComprasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlComprasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlComprasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textTitulo2, javax.swing.GroupLayout.DEFAULT_SIZE, 738, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        pnlComprasLayout.setVerticalGroup(
            pnlComprasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlComprasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textTitulo2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTab.addTab("Compras", pnlCompras);

        jPanelBotones.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });

        btnGrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrabarActionPerformed(evt);
            }
        });

        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnSalir.setMaximumSize(new java.awt.Dimension(90, 30));
        btnSalir.setMinimumSize(new java.awt.Dimension(90, 30));
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelBotonesLayout = new javax.swing.GroupLayout(jPanelBotones);
        jPanelBotones.setLayout(jPanelBotonesLayout);
        jPanelBotonesLayout.setHorizontalGroup(
            jPanelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBotonesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnImagen1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGrabar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelBotonesLayout.setVerticalGroup(
            jPanelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBotonesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnImagen1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnGrabar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTab, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanelTitulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanelBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        this.Editar('M');
    }//GEN-LAST:event_btnModificarActionPerformed

    private void cboEstadoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cboEstadoFocusGained
        this.cboEstado.setPopupVisible(true);
    }//GEN-LAST:event_cboEstadoFocusGained

    private void cboACreditoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cboACreditoFocusGained
        this.cboACredito.setPopupVisible(true);
    }//GEN-LAST:event_cboACreditoFocusGained

    private void txtCod_ContactoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCod_ContactoActionPerformed
        int valor = this.txtCod_Contacto.verificarVacioConMsj();
        if (valor == 0) {
            this.txtCod_Contacto.setEnabled(false);
            if (operacion == 'M' || operacion == 'E') {
                this.RecuperarDatos(this.txtCod_Contacto.getText());
            } else {
                this.txtCINumero.grabFocus();
            }
        } else if (valor == 1) {
            this.Inicializar();
        }
    }//GEN-LAST:event_txtCod_ContactoActionPerformed

    private void txtCINumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCINumeroActionPerformed
        this.txtRuc.grabFocus();
    }//GEN-LAST:event_txtCINumeroActionPerformed

    private void txtRazonSocialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRazonSocialActionPerformed
        int valor = this.txtRazonSocial.verificarVacioConMsj();
        if (valor == 0) {
            this.txtTelefono.grabFocus();
        } else if (valor == 1) {
            this.Inicializar();
        }
    }//GEN-LAST:event_txtRazonSocialActionPerformed

    private void txtCelularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCelularActionPerformed
        this.txtTelefax1.grabFocus();
    }//GEN-LAST:event_txtCelularActionPerformed

    private void txtDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDireccionActionPerformed
        int valor = this.txtDireccion.verificarVacioConMsj();
        if (valor == 0) {
            this.txtEmail.grabFocus();
        } else if (valor == 1) {
            this.Inicializar();
        }
    }//GEN-LAST:event_txtDireccionActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        if (ClaseUtilidades.verificarMail(this.txtEmail.getText())) {
            this.txtCod_Nacionalidad.grabFocus();
        } else {
            int msn = MensajeSistema.MensajeOpciones(this, "El Correo Electrónico ingresado no es correcto...",
                    new Object[]{"Continuar", "Reintentar"}, 0);
            if (msn == 0) {
                this.txtEmail.setText("");
                this.txtCod_Nacionalidad.grabFocus();
            } else {
                this.txtEmail.grabFocus();
            }
        }
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtCod_NacionalidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCod_NacionalidadActionPerformed
        int valor = this.txtCod_Nacionalidad.verificarVacioConMsj();
        if (valor == 0) {
            String rs = this.getConexion.getDescripcion(txtCod_Nacionalidad.getBdTabla(), txtCod_Nacionalidad.getBdDescrip(),
                    new String[]{cod_empresa, txtCod_Nacionalidad.getBdCodigo()},
                    new String[]{Configuracion.getCOD_EMPRESA(), this.txtCod_Nacionalidad.getText()});
            if (rs != null) {
                this.textNom_Nacionalidad.setText(rs);
                this.txtCod_Ciudad.grabFocus();
            } else {
                if (MensajeSistema.ConsultaSQLVacio(this)) {
                    this.txtCod_Nacionalidad.setText("");
                    this.textNom_Nacionalidad.setText("");
                    this.txtCod_Nacionalidad.grabFocus();
                } else {
                    this.Inicializar();
                }
            }
        } else if (valor == 1) {
            this.Inicializar();
        }
    }//GEN-LAST:event_txtCod_NacionalidadActionPerformed

    private void txtCod_CiudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCod_CiudadActionPerformed
        int valor = this.txtCod_Ciudad.verificarVacioConMsj();
        if (valor == 0) {
            String rs = this.getConexion.getDescripcion(txtCod_Ciudad.getBdTabla(), txtCod_Ciudad.getBdTabla(),
                    new String[]{cod_empresa, txtCod_Ciudad.getBdCodigo()},
                    new String[]{Configuracion.getCOD_EMPRESA(), this.txtCod_Ciudad.getText()});
            if (rs != null) {
                this.textNom_Ciudad.setText(rs);
                this.cboEstado.grabFocus();
            } else {
                if (MensajeSistema.ConsultaSQLVacio(this)) {
                    this.txtCod_Ciudad.setText("");
                    this.textNom_Ciudad.setText("");
                    this.txtCod_Ciudad.grabFocus();
                } else {
                    this.Inicializar();
                }
            }
        } else if (valor == 1) {
            this.Inicializar();
        }
    }//GEN-LAST:event_txtCod_CiudadActionPerformed

    private void txtCod_NacionalidadKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCod_NacionalidadKeyPressed
        if (evt.getKeyCode() == ClaseTeclas.VK_F5()) {
            this.Buscar(txtCod_Nacionalidad.getBdTabla(), true, false,
                    txtCod_Nacionalidad.getBdCodigo(), txtCod_Nacionalidad.getBdDescrip(), txtCod_Nacionalidad.getBdTitulo());
            this.txtCod_Nacionalidad.requestFocus();
        }
    }//GEN-LAST:event_txtCod_NacionalidadKeyPressed

    private void txtCod_CiudadKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCod_CiudadKeyPressed
        if (evt.getKeyCode() == ClaseTeclas.VK_F5()) {
            this.Buscar(txtCod_Ciudad.getBdTabla(), true, false,
                    txtCod_Ciudad.getBdCodigo(), txtCod_Ciudad.getBdDescrip(), txtCod_Ciudad.getBdTitulo());
            this.txtCod_Ciudad.requestFocus();
        }
    }//GEN-LAST:event_txtCod_CiudadKeyPressed

    private void cboEstadoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cboEstadoKeyPressed
        if (evt.getKeyCode() == ClaseTeclas.VK_ENTER()) {
            if (this.cboEstado.getSelectedIndex() == 0) {
                MensajeSistema.MensajeVarios(this, "Seleccione un registro...", MensajeSistema.ERROR_MESSAGE());
                this.cboEstado.grabFocus();
            } else {
                this.cboACredito.grabFocus();
            }
        }
    }//GEN-LAST:event_cboEstadoKeyPressed

    private void cboACreditoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cboACreditoKeyPressed
        if (evt.getKeyCode() == ClaseTeclas.VK_ENTER()) {
            if (this.cboACredito.getSelectedIndex() == 0) {
                MensajeSistema.MensajeVarios(this, "Seleccione un registro...", MensajeSistema.ERROR_MESSAGE());
                this.cboACredito.grabFocus();
            } else {
                this.cboRetentor.grabFocus();
            }
        }
    }//GEN-LAST:event_cboACreditoKeyPressed

    private void cboRetentorFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cboRetentorFocusGained
        this.cboRetentor.setPopupVisible(true);
    }//GEN-LAST:event_cboRetentorFocusGained

    private void cboRetentorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cboRetentorKeyPressed
        if (evt.getKeyCode() == ClaseTeclas.VK_ENTER()) {
            if (this.cboRetentor.getSelectedIndex() == 0) {
                MensajeSistema.MensajeVarios(this, "Seleccione un registro...", MensajeSistema.ERROR_MESSAGE());
                this.cboRetentor.grabFocus();
            } else {
                this.btnGrabar.setEnabled(true);
                this.btnGrabar.grabFocus();
            }
        }
    }//GEN-LAST:event_cboRetentorKeyPressed

    private void txtCod_ContactoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCod_ContactoKeyPressed
        if (evt.getKeyCode() == ClaseTeclas.VK_F5()) {
            this.Buscar(tablaConsutada, UsarEmpresa, UsarSucursal, idConsultada, descripcionConsultada, tituloVentanaActual);
            this.txtCod_Contacto.requestFocus();
        }
    }//GEN-LAST:event_txtCod_ContactoKeyPressed

    private void txtTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonoActionPerformed
        int valor = this.txtTelefono.verificarVacioConMsj();
        if (valor == 0) {
            this.txtCelular.grabFocus();
        } else if (valor == 1) {
            this.Inicializar();
        }
    }//GEN-LAST:event_txtTelefonoActionPerformed

    private void txtTelefax1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefax1ActionPerformed
        this.txtTelefax2.grabFocus();
    }//GEN-LAST:event_txtTelefax1ActionPerformed

    private void txtTelefax2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefax2ActionPerformed
        this.txtDireccion.grabFocus();
    }//GEN-LAST:event_txtTelefax2ActionPerformed

    private void txtRucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRucActionPerformed
        this.txtRazonSocial.grabFocus();
    }//GEN-LAST:event_txtRucActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        this.Agregar();
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        this.Editar('E');
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void btnGrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrabarActionPerformed
        this.Grabar();
    }//GEN-LAST:event_btnGrabarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        Inicializar();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        Salir(this);
    }//GEN-LAST:event_btnSalirActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.app.botones.btnBorrar btnBorrar;
    private com.app.botones.btnCancelar btnCancelar;
    private com.app.botones.btnGrabar btnGrabar;
    private com.app.botones.btnImagen btnImagen1;
    private com.app.botones.btnEditar btnModificar;
    private com.app.botones.btnNuevo btnNuevo;    
    private com.app.botones.btnSalir btnSalir;
    private javax.swing.JComboBox cboACredito;
    private javax.swing.JComboBox cboEstado;
    private javax.swing.JComboBox cboRetentor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelBotones;
    private javax.swing.JPanel jPanelTitulo;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTab;
    private javax.swing.JPanel pnlCompras;
    private javax.swing.JPanel pnlMantenimiento;
    private javax.swing.JPanel pnlVentas;
    private com.app.paleta.tbl tbltablaCompra;
    private com.app.paleta.tbl tbltablaVenta;
    private javax.swing.JLabel textNom_Ciudad;
    private javax.swing.JLabel textNom_Nacionalidad;
    private javax.swing.JLabel textTitulo;
    private javax.swing.JLabel textTitulo1;
    private javax.swing.JLabel textTitulo2;
    private com.app.paleta.txtNumeros txtCINumero;
    private com.app.paleta.txtCelular txtCelular;
    private com.app.paleta.txtCodigo txtCod_Ciudad;
    private com.app.paleta.txtCodigo txtCod_Contacto;
    private com.app.paleta.txtCodigo txtCod_Nacionalidad;
    private com.app.paleta.txtTexto txtDireccion;
    private com.app.paleta.txtTexto txtEmail;
    private com.app.paleta.txtTexto txtRazonSocial;
    private com.app.paleta.txtNumeros txtRuc;
    private com.app.paleta.txtTelefono txtTelefax1;
    private com.app.paleta.txtTelefono txtTelefax2;
    private com.app.paleta.txtTelefono txtTelefono;
    // End of variables declaration//GEN-END:variables

    @Override
    public void Inicializar() {
        ClaseCampos.setEnabled(pnlMantenimiento, false);
        ClaseCampos.setEnabled(pnlVentas, false);
        ClaseCampos.setEnabled(pnlCompras, false);
        ClaseCampos.SetTextNull(pnlMantenimiento);
        ClaseCampos.SetTextNull(pnlVentas);
        ClaseCampos.SetTextNull(pnlCompras);
        this.jTab.setEnabledAt(1, false);
        this.jTab.setEnabledAt(2, false);
        this.cboACredito.setSelectedIndex(0);
        this.cboEstado.setSelectedIndex(0);
        this.cboRetentor.setSelectedIndex(0);
        this.textNom_Nacionalidad.setText("");
        this.textNom_Ciudad.setText("");
        this.btnNuevo.setEnabled(Agrega_OK);
        this.btnModificar.setEnabled(Modifica_OK);
        this.btnBorrar.setEnabled(Borra_OK);
        this.btnGrabar.setEnabled(false);
        this.btnCancelar.setEnabled(false);
        this.btnSalir.setEnabled(true);
        if (this.btnNuevo.isEnabled()) {
            this.btnNuevo.grabFocus();
        } else if (this.btnModificar.isEnabled()) {
            this.btnModificar.grabFocus();
        } else if (this.btnBorrar.isEnabled()) {
            this.btnBorrar.grabFocus();
        } else {
            this.btnSalir.grabFocus();
        }
    }

    @Override
    public void Agregar() {
        this.jTab.setSelectedIndex(0);
        this.jTab.setEnabledAt(1, false);
        this.jTab.setEnabledAt(2, false);
        if (getConexion.autoNumerico(tablaConsutada, idConsultada,
                new String[]{cod_empresa}, new String[]{Configuracion.getCOD_EMPRESA()}, this.txtCod_Contacto)) {
            ClaseBotones.modoEdicionABM(btnNuevo, btnModificar, btnBorrar, btnGrabar, btnCancelar, btnSalir, false);
            ClaseCampos.setEnabled(pnlMantenimiento, true);
            this.btnGrabar.setEnabled(false);
            operacion = 'A';
            this.txtCod_Contacto.grabFocus();
        } else {
            Inicializar();
        }
    }

    @Override
    public void Grabar() {
        if (operacion == 'A') {
            if (MensajeSistema.Guardar(this)) {
                getConexion.insertar(tablaConsutada,
                        new String[]{cod_empresa, idConsultada, descripcionConsultada, "nro_ruc",
                            "nro_ci", "telefono1", "telefono2", "direccion", "email", "telefax1",
                            "telefax2", txtCod_Nacionalidad.getBdCodigo(), txtCod_Ciudad.getBdCodigo(), "agente_retentor",
                            "estado", "a_credito", "cod_usuario"},
                        new String[]{Configuracion.getCOD_EMPRESA(), this.txtCod_Contacto.getText(),
                            this.txtRazonSocial.getText(), this.txtRuc.getText(), this.txtCINumero.getText(),
                            this.txtTelefono.getText().trim(), this.txtCelular.getText(), this.txtDireccion.getText(),
                            this.txtEmail.getText().trim(), this.txtTelefax1.getText().trim(), this.txtTelefax2.getText().trim(),
                            this.txtCod_Nacionalidad.getText(), this.txtCod_Ciudad.getText(), this.cboRetentor.getSelectedIndex() + "",
                            this.cboEstado.getSelectedIndex() + "", this.cboACredito.getSelectedIndex() + "",
                            Configuracion.getCOD_USUARIO()});
            }
        } else {
            if (MensajeSistema.Modificar(this)) {
                getConexion.actualizar(tablaConsutada,
                        new String[]{descripcionConsultada, "nro_ruc",
                            "nro_ci", "telefono1", "telefono2", "direccion", "email", "telefax1",
                            "telefax2", txtCod_Nacionalidad.getBdCodigo(), txtCod_Ciudad.getBdCodigo(), "agente_retentor",
                            "estado", "a_credito"},
                        new String[]{this.txtRazonSocial.getText(), this.txtRuc.getText(), this.txtCINumero.getText(),
                            this.txtTelefono.getText().trim(), this.txtCelular.getText(), this.txtDireccion.getText(),
                            this.txtEmail.getText().trim(), this.txtTelefax1.getText().trim(), this.txtTelefax2.getText().trim(),
                            this.txtCod_Nacionalidad.getText(), this.txtCod_Ciudad.getText(), this.cboRetentor.getSelectedIndex() + "",
                            this.cboEstado.getSelectedIndex() + "", this.cboACredito.getSelectedIndex() + ""},
                        new String[]{cod_empresa, idConsultada},
                        new String[]{Configuracion.getCOD_EMPRESA(), this.txtCod_Contacto.getText()});
            }
        }
        this.Inicializar();
    }

    @Override
    public void Editar(char c) {
        operacion = c;
        ClaseBotones.modoEdicionABM(btnNuevo, btnModificar, btnBorrar, btnGrabar, btnCancelar, btnSalir, false);
        this.txtCod_Contacto.setEnabled(true);
        this.btnGrabar.setEnabled(false);
        this.txtCod_Contacto.grabFocus();
    }

    @Override
    public void RecuperarDatos(String codigo) {
        String[] rs = getConexion.getDescripciones("vst_" + tablaConsutada,
                new String[]{cod_empresa, idConsultada, descripcionConsultada, "nro_ruc",
                    "nro_ci", "telefono1", "telefono2", "direccion", "email", "telefax1",
                    "telefax2", txtCod_Nacionalidad.getBdCodigo(), txtCod_Nacionalidad.getBdDescrip(),
                    txtCod_Ciudad.getBdCodigo(), txtCod_Ciudad.getBdDescrip(), "agente_retentor", "estado", "a_credito"},
                new String[]{cod_empresa, idConsultada},
                new String[]{Configuracion.getCOD_EMPRESA(), codigo});
        if (rs[0] != null) {
            this.txtRazonSocial.setText(rs[2]);
            this.txtRuc.setText(rs[3]);
            this.txtCINumero.setText(rs[4]);
            this.txtTelefono.setText(rs[5]);
            this.txtCelular.setText(rs[6]);
            this.txtDireccion.setText(rs[7]);
            this.txtEmail.setText(rs[8]);
            this.txtTelefax1.setText(rs[9]);
            this.txtTelefax2.setText(rs[10]);
            this.txtCod_Nacionalidad.setText(rs[11]);
            this.textNom_Nacionalidad.setText(rs[12]);
            this.txtCod_Ciudad.setText(rs[13]);
            this.textNom_Ciudad.setText(rs[14]);
            this.cboRetentor.setSelectedIndex(Integer.parseInt(rs[15]));
            this.cboEstado.setSelectedIndex(Integer.parseInt(rs[16]));
            this.cboACredito.setSelectedIndex(Integer.parseInt(rs[17]));
            if (operacion == 'E') {
                Borrar(this, tablaConsutada,
                        new String[]{cod_empresa, idConsultada},
                        new String[]{Configuracion.getCOD_EMPRESA(), codigo});
                Inicializar();
            } else if (operacion == 'M') {
                ClaseCampos.setEnabled(pnlMantenimiento, true);
                this.recuperarSaldos(codigo);
                this.txtCod_Contacto.setEnabled(false);
                this.txtCINumero.grabFocus();
            }
        } else {
            if (MensajeSistema.ConsultaSQLVacio(this)) {
                this.txtCod_Contacto.setText("");
                this.txtCod_Contacto.setEnabled(true);
                this.txtCod_Contacto.grabFocus();
            } else {
                this.Inicializar();
            }
        }
    }

    public void recuperarSaldos(String codigo) {
        String sqlC = ConsultaSQL.getSelect("vst_" + tablaConsutada + "_saldos",
                new String[]{"Mon_Denom", "total_compra_saldo_ant", "total_compra_con", "total_compra_cre",
                    "total_compra_pago", "total_compra_intgen", "total_compra_saldos"},
                new String[]{},
                new String[]{cod_empresa, cod_sucursal, idConsultada},
                new String[]{Configuracion.getCOD_EMPRESA(), Configuracion.getCOD_SUCURSAL(), codigo});
        this.tbltablaCompra.cargarDatos(getConexion, sqlC);
        this.tbltablaCompra.setAlinearDerecha(new int[]{1, 2, 3, 4, 5, 6});
        this.tbltablaCompra.setAlinearCentro(0);
        this.tbltablaCompra.formatearColumna(new int[]{1, 2, 3, 4, 5, 6}, 0);
        this.tbltablaCompra.setAncho(0, 30);
        this.jTab.setEnabledAt(1, true);
        String sqlV = ConsultaSQL.getSelect("vst_" + tablaConsutada + "_saldos",
                new String[]{"Mon_Denom", "total_venta_saldo_ant", "total_venta_con", "total_venta_cre",
                    "total_venta_cobro", "total_venta_intgen", "total_venta_saldos"},
                new String[]{},
                new String[]{cod_empresa, cod_sucursal, idConsultada},
                new String[]{Configuracion.getCOD_EMPRESA(), Configuracion.getCOD_SUCURSAL(), codigo});
        this.tbltablaVenta.cargarDatos(getConexion, sqlV);
        this.tbltablaVenta.setAlinearDerecha(new int[]{1, 2, 3, 4, 5, 6});
        this.tbltablaVenta.setAlinearCentro(0);
        this.tbltablaVenta.formatearColumna(new int[]{1, 2, 3, 4, 5, 6}, 0);
        this.tbltablaVenta.setAncho(0, 30);
        this.jTab.setEnabledAt(2, true);
    }
}
