package com.app.form;

import com.app.clases.ClaseBotones;
import com.app.clases.ClaseCampos;
import com.app.clases.ClaseTeclas;
import com.app.config.Configuracion;
import com.app.config.MensajeSistema;
import com.app.form.Especiales.frm_Padre.Metodos;
import com.app.form.Especiales.frm_Padre;

/**
 *
 * @author Diego
 */
public final class Productos extends frm_Padre implements Metodos {

    private int vTipo;
    private boolean recuperado;

    public Productos(int cod_ventana) {
        initComponents();
        this.setName("productos");
        this.textTitulo.setText("Mantenimiento de Productos...");
        this.getPermisos(cod_ventana);
        ClaseBotones.botonesABMKeyPressed(btnNuevo, btnModificar, btnBorrar, btnGrabar, btnCancelar, btnSalir);
        this.txtCod_Producto.setTextTransparente("Ingrese el codigo del Producto");
        this.txtCod_Barra.setTextTransparente("Ingrese el codigo de barra");
        this.txtNombre_Producto.setTextTransparente("Ingrese el nombre del Producto");
        this.txtEstante.setTextTransparente("Estante");
        this.txtColumna.setTextTransparente("Columna");
        this.txtFila.setTextTransparente("Fila");
        this.txtCod_Barra.setEnMayuscula(true);
        this.txtCosto_Actual.setInicializar(15, 0);
        this.txtCosto_Inicial.setInicializar(15, 0);
        this.txtPrecioV_Actual.setInicializar(15, 0);
        this.txtPrecioV_Inicial.setInicializar(15, 0);
        this.txtCosto_Actual.setFormatear(true);
        this.txtCosto_Inicial.setFormatear(true);
        this.txtPrecioV_Actual.setFormatear(true);
        this.txtPrecioV_Inicial.setFormatear(true);

        this.txtCod_Producto.setBdTabla("mant_Productos");
        this.txtCod_Producto.setBdCodigo("Prod_Codigo");
        this.txtCod_Producto.setBdDescrip("Prod_Descrip");
        this.txtCod_Producto.setBdTitulo("Productos");
        this.txtCod_Producto.setUsarEmpresa(true);
        this.txtCod_Producto.setUsarSucursal(false);

        this.txtCod_Seccion.setBdTabla("Ref_Secciones");
        this.txtCod_Seccion.setBdCodigo("Sec_Codigo");
        this.txtCod_Seccion.setBdDescrip("Sec_Descrip");
        this.txtCod_Seccion.setBdTitulo("Secciones");
        this.txtCod_Seccion.setUsarEmpresa(true);
        this.txtCod_Seccion.setUsarSucursal(false);

        this.txtCod_Procedencia.setBdTabla("Ref_Nacionalidades");
        this.txtCod_Procedencia.setBdCodigo("Nac_Codigo");
        this.txtCod_Procedencia.setBdDescrip("Nac_Descrip");
        this.txtCod_Procedencia.setBdTitulo("Procedencias");
        this.txtCod_Procedencia.setUsarEmpresa(true);
        this.txtCod_Procedencia.setUsarSucursal(false);

        this.txtCod_Marca.setBdTabla("Ref_Marcas");
        this.txtCod_Marca.setBdCodigo("Mar_Codigo");
        this.txtCod_Marca.setBdDescrip("Mar_Descrip");
        this.txtCod_Marca.setBdTitulo("Marcas");
        this.txtCod_Marca.setUsarEmpresa(true);
        this.txtCod_Marca.setUsarSucursal(false);

        this.txtCod_Envace.setBdTabla("Ref_Envaces");
        this.txtCod_Envace.setBdCodigo("Env_Codigo");
        this.txtCod_Envace.setBdDescrip("Env_Descrip");
        this.txtCod_Envace.setBdTitulo("Envaces");
        this.txtCod_Envace.setUsarEmpresa(true);
        this.txtCod_Envace.setUsarSucursal(false);

        this.txtCod_Linea.setBdTabla("Ref_Lineas");
        this.txtCod_Linea.setBdCodigo("Lin_Codigo");
        this.txtCod_Linea.setBdDescrip("Lin_Descrip");
        this.txtCod_Linea.setBdTitulo("Lineas");
        this.txtCod_Linea.setUsarEmpresa(true);
        this.txtCod_Linea.setUsarSucursal(false);
        this.cboTipoProducto.addItem(new String[]{"1", "2", "3", "4", "5"}, new String[]{"MERCADERIA", "SERVICIOS", "ACTIVO FIJO", "CONTRATO", "GASTOS"});
        this.cboIva.addItem(new String[]{"1", "2", "3"}, new String[]{"EXENTA", "IVA 05 %", "IVA 10 %"});

        Inicializar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanelTitulo = new javax.swing.JPanel();
        textTitulo = new javax.swing.JLabel();
        jTab = new javax.swing.JTabbedPane();
        jPanelDatos = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtCod_Producto = new com.app.paleta.txtCodigo();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtCod_Procedencia = new com.app.paleta.txtCodigo();
        textNom_Procedencia = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtCod_Envace = new com.app.paleta.txtCodigo();
        textNom_Envace = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtCod_Marca = new com.app.paleta.txtCodigo();
        textNom_Marca = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtCod_Linea = new com.app.paleta.txtCodigo();
        textNom_Linea = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        txtFactor = new com.app.paleta.txtNumeros();
        jLabel17 = new javax.swing.JLabel();
        txtCosto_Inicial = new com.app.paleta.txtNumeros();
        jLabel19 = new javax.swing.JLabel();
        txtPrecioV_Inicial = new com.app.paleta.txtNumeros();
        jLabel15 = new javax.swing.JLabel();
        txtDescuento = new com.app.paleta.txtNumeros();
        jLabel18 = new javax.swing.JLabel();
        txtCosto_Actual = new com.app.paleta.txtNumeros();
        jLabel20 = new javax.swing.JLabel();
        txtPrecioV_Actual = new com.app.paleta.txtNumeros();
        jSeparator2 = new javax.swing.JSeparator();
        jCheckPedesedero = new javax.swing.JCheckBox();
        jCheckControlado = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtStockMinimo = new com.app.paleta.txtNumeros();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtComentario = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        txtEstante = new com.app.paleta.txtNumeros();
        txtColumna = new com.app.paleta.txtNumeros();
        txtFila = new com.app.paleta.txtNumeros();
        txtNombre_Producto = new com.app.paleta.txtTexto();
        txtCod_Barra = new com.app.paleta.txtTexto();
        jLabel11 = new javax.swing.JLabel();
        txtCod_Seccion = new com.app.paleta.txtCodigo();
        textNom_Seccion = new javax.swing.JLabel();
        cboTipoProducto = new com.app.paleta.combo();
        cboIva = new com.app.paleta.combo();
        jPanel2 = new javax.swing.JPanel();
        jPanelBotones = new javax.swing.JPanel();
        btnImagen1 = new com.app.botones.btnImagen();
        btnNuevo = new com.app.botones.btnNuevo();
        btnModificar = new com.app.botones.btnEditar();
        btnBorrar = new com.app.botones.btnBorrar();
        btnGrabar = new com.app.botones.btnGrabar();
        btnCancelar = new com.app.botones.btnCancelar();
        btnSalir = new com.app.botones.btnSalir();

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Código:");

        jPanelTitulo.setBackground(new java.awt.Color(204, 204, 204));
        jPanelTitulo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelTitulo.setMaximumSize(new java.awt.Dimension(486, 60));
        jPanelTitulo.setMinimumSize(new java.awt.Dimension(486, 60));

        textTitulo.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        textTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textTitulo.setText("Mantenimiento de Productos...");

        javax.swing.GroupLayout jPanelTituloLayout = new javax.swing.GroupLayout(jPanelTitulo);
        jPanelTitulo.setLayout(jPanelTituloLayout);
        jPanelTituloLayout.setHorizontalGroup(
            jPanelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelTituloLayout.setVerticalGroup(
            jPanelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanelDatos.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Código:");

        txtCod_Producto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCod_ProductoActionPerformed(evt);
            }
        });

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Nombre:");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Código de Barra:");

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Procedencia:");

        txtCod_Procedencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCod_ProcedenciaActionPerformed(evt);
            }
        });

        textNom_Procedencia.setText("jLabel7");

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Envace:");

        txtCod_Envace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCod_EnvaceActionPerformed(evt);
            }
        });

        textNom_Envace.setText("jLabel7");

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Marca:");

        txtCod_Marca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCod_MarcaActionPerformed(evt);
            }
        });

        textNom_Marca.setText("jLabel7");

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("Linea:");

        txtCod_Linea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCod_LineaActionPerformed(evt);
            }
        });

        textNom_Linea.setText("jLabel7");

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Factor");

        txtFactor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFactorActionPerformed(evt);
            }
        });

        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel17.setText("Costo Inicial:");

        txtCosto_Inicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCosto_InicialActionPerformed(evt);
            }
        });

        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel19.setText("Precio V. Inicial:");

        txtPrecioV_Inicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecioV_InicialActionPerformed(evt);
            }
        });

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Descuento");

        txtDescuento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescuentoActionPerformed(evt);
            }
        });

        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel18.setText("Costo Actual:");

        txtCosto_Actual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCosto_ActualActionPerformed(evt);
            }
        });

        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel20.setText("Precio V. Actual:");

        txtPrecioV_Actual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecioV_ActualActionPerformed(evt);
            }
        });

        jCheckPedesedero.setText("Peresedero");
        jCheckPedesedero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jCheckPedesederoKeyPressed(evt);
            }
        });

        jCheckControlado.setText("Controlado");
        jCheckControlado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jCheckControladoKeyPressed(evt);
            }
        });

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("IVA:");

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Ubicación:");

        txtStockMinimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStockMinimoActionPerformed(evt);
            }
        });

        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Stock Mínimo");

        txtComentario.setColumns(20);
        txtComentario.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        txtComentario.setRows(5);
        jScrollPane1.setViewportView(txtComentario);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Tipo Producto:");

        txtEstante.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtEstanteKeyPressed(evt);
            }
        });

        txtColumna.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtColumnaKeyPressed(evt);
            }
        });

        txtFila.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtFilaKeyPressed(evt);
            }
        });

        txtNombre_Producto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombre_ProductoActionPerformed(evt);
            }
        });
        txtNombre_Producto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombre_ProductoKeyTyped(evt);
            }
        });

        txtCod_Barra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCod_BarraActionPerformed(evt);
            }
        });
        txtCod_Barra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCod_BarraKeyTyped(evt);
            }
        });

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("Sección:");

        txtCod_Seccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCod_SeccionActionPerformed(evt);
            }
        });

        textNom_Seccion.setText("jLabel7");

        cboTipoProducto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cboTipoProductoFocusGained(evt);
            }
        });
        cboTipoProducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cboTipoProductoKeyPressed(evt);
            }
        });

        cboIva.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cboIvaFocusGained(evt);
            }
        });
        cboIva.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cboIvaKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanelDatosLayout = new javax.swing.GroupLayout(jPanelDatos);
        jPanelDatos.setLayout(jPanelDatosLayout);
        jPanelDatosLayout.setHorizontalGroup(
            jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDatosLayout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(jPanelDatosLayout.createSequentialGroup()
                        .addComponent(jCheckPedesedero, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckControlado, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboTipoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboIva, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEstante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                        .addComponent(txtColumna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFila, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanelDatosLayout.createSequentialGroup()
                        .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelDatosLayout.createSequentialGroup()
                                .addComponent(txtCod_Producto, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNombre_Producto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanelDatosLayout.createSequentialGroup()
                                .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtCod_Barra, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelDatosLayout.createSequentialGroup()
                                        .addComponent(txtCod_Marca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(textNom_Marca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelDatosLayout.createSequentialGroup()
                                        .addComponent(txtCod_Procedencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(textNom_Procedencia, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelDatosLayout.createSequentialGroup()
                                        .addComponent(txtCod_Seccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(textNom_Seccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanelDatosLayout.createSequentialGroup()
                                        .addComponent(txtCod_Linea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(textNom_Linea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanelDatosLayout.createSequentialGroup()
                                        .addComponent(txtCod_Envace, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(textNom_Envace, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                        .addContainerGap())
                    .addGroup(jPanelDatosLayout.createSequentialGroup()
                        .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtFactor, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtDescuento, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtStockMinimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCosto_Inicial, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                            .addComponent(txtCosto_Actual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtPrecioV_Actual, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                            .addComponent(txtPrecioV_Inicial, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE))
                        .addGap(45, 45, 45))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDatosLayout.createSequentialGroup()
                        .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1))
                        .addContainerGap())))
        );
        jPanelDatosLayout.setVerticalGroup(
            jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtCod_Producto, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtNombre_Producto, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelDatosLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtCod_Seccion, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(textNom_Seccion, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtCod_Barra, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCod_Procedencia, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textNom_Procedencia, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCod_Envace, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textNom_Envace, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCod_Marca, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textNom_Marca, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCod_Linea, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textNom_Linea, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCosto_Inicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPrecioV_Inicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCosto_Actual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPrecioV_Actual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFactor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtStockMinimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckPedesedero)
                    .addComponent(jCheckControlado)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtEstante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFila, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtColumna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboTipoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboIva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTab.addTab("Productos", jPanelDatos);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 879, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
        );

        jTab.addTab("Stock X Lotes", jPanel2);

        jPanelBotones.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });

        btnGrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrabarActionPerformed(evt);
            }
        });

        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnSalir.setMaximumSize(new java.awt.Dimension(90, 30));
        btnSalir.setMinimumSize(new java.awt.Dimension(90, 30));
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelBotonesLayout = new javax.swing.GroupLayout(jPanelBotones);
        jPanelBotones.setLayout(jPanelBotonesLayout);
        jPanelBotonesLayout.setHorizontalGroup(
            jPanelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBotonesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnImagen1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGrabar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelBotonesLayout.setVerticalGroup(
            jPanelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBotonesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnImagen1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnGrabar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTab))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCod_ProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCod_ProductoActionPerformed
        int valor = this.txtCod_Producto.verificarVacioConMsj();
        if (valor == 0) {
            if (Operacion == 'M' || Operacion == 'E') {
                if (this.recuperado) {
                    this.txtNombre_Producto.grabFocus();
                } else {
                    vTipo = 1;
                    this.txtCod_Producto.setEnabled(false);
                    this.txtCod_Barra.setEnabled(false);
                    this.RecuperarDatos(this.txtCod_Producto.getText());
                }
            } else {
                this.txtNombre_Producto.grabFocus();
            }
        } else if (valor == 1) {
            this.Inicializar();
        }
    }//GEN-LAST:event_txtCod_ProductoActionPerformed

    private void txtNombre_ProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombre_ProductoActionPerformed
        int valor = this.txtNombre_Producto.verificarVacioConMsj();
        if (valor == 0) {
            this.txtCod_Seccion.grabFocus();
        } else if (valor == 1) {
            this.Inicializar();
        }
    }//GEN-LAST:event_txtNombre_ProductoActionPerformed

    private void txtCod_BarraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCod_BarraActionPerformed
        int valor = this.txtCod_Barra.verificarVacioConMsj();
        if (valor == 0) {
            //Cuando es Agregar se verifica si el codigo de barra ya existe en la base de datos
            if (Operacion == 'A') {
                String resu = this.getConexion.getDescripcion(this.txtCod_Producto.getBdTabla(), "Bar_Codigo",
                        new String[]{EMP_CODIGO, "Bar_Codigo"},
                        new String[]{Configuracion.getEMP_CODIGO(), this.txtCod_Barra.getText().trim()});
                if (resu != null) {
                    MensajeSistema.MensajeVarios(this, "Este Código de producto ya existe en la Base de Datos...", MensajeSistema.ERROR_MESSAGE());
                    this.txtCod_Barra.grabFocus();
                } else {
                    this.txtCod_Seccion.grabFocus();
                }
            } else {
                if (this.recuperado) {
                    this.txtCod_Seccion.grabFocus();
                } else {
                    this.txtCod_Producto.setEnabled(false);
                    this.txtNombre_Producto.setEnabled(false);
                    vTipo = 2;
                    this.RecuperarDatos(this.txtCod_Barra.getText());
                }
            }
        } else if (valor == 1) {
            this.Inicializar();
        }
    }//GEN-LAST:event_txtCod_BarraActionPerformed

    private void txtCod_BarraKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCod_BarraKeyTyped
        this.txtCod_Barra.CantidadLetras(evt, 15);
    }//GEN-LAST:event_txtCod_BarraKeyTyped

    private void txtCod_ProcedenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCod_ProcedenciaActionPerformed
        int valor = this.txtCod_Procedencia.verificarVacioConMsj();
        if (valor == 0) {
            String rs = this.txtCod_Procedencia.getDescripcion();
            if (rs != null) {
                this.textNom_Procedencia.setText(rs);
                this.txtCod_Envace.grabFocus();
            } else {
                if (MensajeSistema.ConsultaSQLVacio(this)) {
                    this.txtCod_Procedencia.setText("");
                    this.textNom_Procedencia.setText("");
                    this.txtCod_Procedencia.grabFocus();
                } else {
                    this.Inicializar();
                }
            }
        } else if (valor == 1) {
            this.Inicializar();
        }
    }//GEN-LAST:event_txtCod_ProcedenciaActionPerformed

    private void txtCod_EnvaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCod_EnvaceActionPerformed
        int valor = this.txtCod_Envace.verificarVacioConMsj();
        if (valor == 0) {
            String rs = this.txtCod_Envace.getDescripcion();
            if (rs != null) {
                this.textNom_Envace.setText(rs);
                this.txtCod_Marca.grabFocus();
            } else {
                if (MensajeSistema.ConsultaSQLVacio(this)) {
                    this.txtCod_Envace.setText("");
                    this.textNom_Envace.setText("");
                    this.txtCod_Envace.grabFocus();
                } else {
                    this.Inicializar();
                }
            }
        } else if (valor == 1) {
            this.Inicializar();
        }
    }//GEN-LAST:event_txtCod_EnvaceActionPerformed

    private void txtCod_MarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCod_MarcaActionPerformed
        int valor = this.txtCod_Marca.verificarVacioConMsj();
        if (valor == 0) {
            String rs = this.txtCod_Marca.getDescripcion();
            if (rs != null) {
                this.textNom_Marca.setText(rs);
                this.txtCod_Linea.grabFocus();
            } else {
                if (MensajeSistema.ConsultaSQLVacio(this)) {
                    this.txtCod_Marca.setText("");
                    this.textNom_Marca.setText("");
                    this.txtCod_Marca.grabFocus();
                } else {
                    this.Inicializar();
                }
            }
        } else if (valor == 1) {
            this.Inicializar();
        }
    }//GEN-LAST:event_txtCod_MarcaActionPerformed

    private void txtCod_LineaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCod_LineaActionPerformed
        int valor = this.txtCod_Linea.verificarVacioConMsj();
        if (valor == 0) {
            String rs = this.txtCod_Linea.getDescripcion();
            if (rs != null) {
                this.textNom_Linea.setText(rs);
                if (Operacion == 'A') {
                    this.txtFactor.setText("50");
                }
                this.txtFactor.grabFocus();
            } else {
                if (MensajeSistema.ConsultaSQLVacio(this)) {
                    this.txtCod_Linea.setText("");
                    this.textNom_Linea.setText("");
                    this.txtCod_Linea.grabFocus();
                } else {
                    this.Inicializar();
                }
            }
        } else if (valor == 1) {
            this.Inicializar();
        }
    }//GEN-LAST:event_txtCod_LineaActionPerformed

    private void txtFactorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFactorActionPerformed
        if (this.txtFactor.getNumeroInt() <= 0) {
            MensajeSistema.MensajeVarios(this, "El Factor tiene que ser mayor a Cero...", MensajeSistema.INFORMATION_MESSAGE());
            this.txtFactor.setText("50");
            this.txtFactor.grabFocus();
        } else {
            this.txtDescuento.grabFocus();
        }
    }//GEN-LAST:event_txtFactorActionPerformed

    private void txtCosto_InicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCosto_InicialActionPerformed
        if (this.txtCosto_Inicial.getNumeroInt() < 0) {
            MensajeSistema.MensajeVarios(this, "El Precio de Costo no puede ser menor a Cero", MensajeSistema.INFORMATION_MESSAGE());
            this.txtCosto_Inicial.setText("");
            this.txtCosto_Inicial.grabFocus();
        } else {
            this.txtCosto_Actual.setNumero(this.txtCosto_Inicial.getNumeroInt());
            double vVenta = ((this.txtCosto_Inicial.getNumeroInt() * this.txtFactor.getNumeroInt()) / 100) + this.txtCosto_Inicial.getNumeroInt();
            this.txtPrecioV_Inicial.setNumero(vVenta);
            this.txtPrecioV_Inicial.grabFocus();
        }
    }//GEN-LAST:event_txtCosto_InicialActionPerformed

    private void txtPrecioV_InicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecioV_InicialActionPerformed
        if (this.txtPrecioV_Inicial.getNumeroInt() < this.txtCosto_Inicial.getNumeroInt()) {
            MensajeSistema.MensajeVarios(this, "El Precio de Venta no puede ser menor a Costo", MensajeSistema.INFORMATION_MESSAGE());
            this.txtPrecioV_Inicial.setNumero(((this.txtCosto_Inicial.getNumeroInt() * this.txtFactor.getNumeroInt()) / 100) + this.txtCosto_Inicial.getNumeroInt());
            this.txtPrecioV_Inicial.grabFocus();
        } else {
            this.txtPrecioV_Actual.setNumero(this.txtPrecioV_Inicial.getNumeroInt());
            this.jCheckPedesedero.grabFocus();
        }
    }//GEN-LAST:event_txtPrecioV_InicialActionPerformed

    private void txtDescuentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescuentoActionPerformed
        if (this.txtDescuento.getNumeroInt() < 0) {
            MensajeSistema.MensajeVarios(this, "El Descuento no puede ser menor a Cero...", MensajeSistema.INFORMATION_MESSAGE());
            this.txtDescuento.setNumero(this.txtFactor.getNumeroInt() / 2);
            this.txtDescuento.grabFocus();
        } else {
            if (this.txtDescuento.getNumeroInt() > (this.txtFactor.getNumeroInt() / 2)) {
                MensajeSistema.MensajeVarios(this, "El Descuento no puede ser mayor a la mitad del Factor!!!", MensajeSistema.ERROR_MESSAGE());
                this.txtDescuento.setNumero(this.txtFactor.getNumeroInt() / 2);
                this.txtDescuento.grabFocus();
            } else {
                if (this.txtDescuento.getText().isEmpty()) {
                    this.txtDescuento.setNumero(0);
                }
                this.txtStockMinimo.grabFocus();
            }
        }
    }//GEN-LAST:event_txtDescuentoActionPerformed

    private void txtCosto_ActualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCosto_ActualActionPerformed
        if (this.txtCosto_Actual.getNumeroInt() < 0) {
            MensajeSistema.MensajeVarios(this, "El Precio de Costo no puede ser menor a Cero", MensajeSistema.INFORMATION_MESSAGE());
            this.txtCosto_Actual.setText("");
            this.txtCosto_Actual.grabFocus();
        } else {
            double vVenta = ((this.txtCosto_Actual.getNumeroInt() * this.txtFactor.getNumeroInt()) / 100) + this.txtCosto_Actual.getNumeroInt();
            this.txtPrecioV_Actual.setNumero(vVenta);
            this.txtPrecioV_Actual.grabFocus();
        }
    }//GEN-LAST:event_txtCosto_ActualActionPerformed

    private void txtPrecioV_ActualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecioV_ActualActionPerformed
        if (this.txtPrecioV_Actual.getNumeroInt() < this.txtCosto_Actual.getNumeroInt()) {
            MensajeSistema.MensajeVarios(this, "El Precio de Venta no puede ser menor a Costo", MensajeSistema.INFORMATION_MESSAGE());
            this.txtPrecioV_Actual.setNumero((this.txtCosto_Actual.getNumeroInt() * this.txtFactor.getNumeroInt() / 100) + this.txtPrecioV_Actual.getNumeroInt());
            this.txtPrecioV_Actual.grabFocus();
        } else {
            this.jCheckPedesedero.grabFocus();
        }
    }//GEN-LAST:event_txtPrecioV_ActualActionPerformed

    private void jCheckPedesederoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jCheckPedesederoKeyPressed
        if (evt.getKeyCode() == ClaseTeclas.VK_ENTER() || evt.getKeyCode() == ClaseTeclas.VK_SIGUIENTE()) {
            this.jCheckControlado.grabFocus();
        } else if (evt.getKeyCode() == ClaseTeclas.VK_ATRAS()) {
            this.jCheckControlado.grabFocus();
        } else if (evt.getKeyCode() == ClaseTeclas.VK_ESPACIO()) {
            this.jCheckPedesedero.setSelected(true);
            this.jCheckControlado.grabFocus();
        }
    }//GEN-LAST:event_jCheckPedesederoKeyPressed

    private void jCheckControladoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jCheckControladoKeyPressed
        if (evt.getKeyCode() == ClaseTeclas.VK_ENTER() || evt.getKeyCode() == ClaseTeclas.VK_SIGUIENTE()) {
            this.cboTipoProducto.grabFocus();
        } else if (evt.getKeyCode() == ClaseTeclas.VK_ATRAS()) {
            this.jCheckPedesedero.grabFocus();
        } else if (evt.getKeyCode() == ClaseTeclas.VK_ESPACIO()) {
            this.jCheckControlado.setSelected(true);
            this.cboTipoProducto.grabFocus();
        }
    }//GEN-LAST:event_jCheckControladoKeyPressed

    private void txtStockMinimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStockMinimoActionPerformed
        if (this.txtStockMinimo.getNumeroInt() < 0) {
            MensajeSistema.MensajeVarios(this, "No puede ser menor a Cero...\nVerifique y vuelva a intentar!", MensajeSistema.ERROR_MESSAGE());
            this.txtStockMinimo.setNumero(0);
            this.txtStockMinimo.grabFocus();
        } else {
            if (this.txtStockMinimo.getText().isEmpty()) {
                this.txtStockMinimo.setNumero(0);
            }
            if (Operacion == 'A') {
                this.txtCosto_Inicial.grabFocus();
            } else {
                this.txtCosto_Actual.grabFocus();
            }
        }
    }//GEN-LAST:event_txtStockMinimoActionPerformed

    private void txtEstanteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEstanteKeyPressed
        if (evt.getKeyCode() == ClaseTeclas.VK_ENTER()) {
            if (this.txtEstante.getNumeroInt() < 0) {
                MensajeSistema.MensajeVarios(this, "El valor de este campo no puede ser menor a Cero...", MensajeSistema.ERROR_MESSAGE());
                this.txtEstante.setNumero(0);
            } else {
                if (this.txtEstante.getNumeroInt() == 0) {
                    this.txtComentario.setEnabled(true);
                    this.btnGrabar.setEnabled(true);
                    this.txtColumna.setEnabled(false);
                    this.txtFila.setEnabled(false);
                    this.txtEstante.setNumero(0);
                    this.txtColumna.setNumero(0);
                    this.txtFila.setNumero(0);
                    this.txtComentario.grabFocus();
                } else {
                    this.txtColumna.grabFocus();
                }
            }
        }
    }//GEN-LAST:event_txtEstanteKeyPressed

    private void txtColumnaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtColumnaKeyPressed
        if (evt.getKeyCode() == ClaseTeclas.VK_ENTER()) {
            if (this.txtColumna.getNumeroInt() < 0) {
                MensajeSistema.MensajeVarios(this, "El valor de este campo no puede ser menor a Cero...", MensajeSistema.ERROR_MESSAGE());
                this.txtColumna.setNumero(0);
            } else {
                this.txtFila.grabFocus();
            }
        }
    }//GEN-LAST:event_txtColumnaKeyPressed

    private void txtFilaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFilaKeyPressed
        if (evt.getKeyCode() == ClaseTeclas.VK_ENTER()) {
            if (this.txtFila.getNumeroInt() < 0) {
                MensajeSistema.MensajeVarios(this, "El valor de este campo no puede ser menor a Cero...", MensajeSistema.ERROR_MESSAGE());
                this.txtFila.setNumero(0);
            } else {
                this.txtComentario.setEnabled(true);
                this.btnGrabar.setEnabled(true);
                this.txtComentario.grabFocus();
            }
        }
    }//GEN-LAST:event_txtFilaKeyPressed

    private void txtNombre_ProductoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombre_ProductoKeyTyped
        this.txtNombre_Producto.CantidadLetras(evt, 250);
    }//GEN-LAST:event_txtNombre_ProductoKeyTyped

    private void txtCod_SeccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCod_SeccionActionPerformed
        int valor = this.txtCod_Seccion.verificarVacioConMsj();
        if (valor == 0) {
            String rs = this.getConexion.getDescripcion(this.txtCod_Seccion.getBdTabla(), this.txtCod_Seccion.getBdDescrip(),
                    new String[]{EMP_CODIGO, this.txtCod_Seccion.getBdCodigo()},
                    new String[]{Configuracion.getEMP_CODIGO(), this.txtCod_Seccion.getText()});
            if (rs != null) {
                this.textNom_Seccion.setText(rs);
                this.txtCod_Procedencia.grabFocus();
            } else {
                if (MensajeSistema.ConsultaSQLVacio(this)) {
                    this.txtCod_Seccion.setText("");
                    this.textNom_Seccion.setText("");
                    this.txtCod_Seccion.grabFocus();
                } else {
                    this.Inicializar();
                }
            }
        } else if (valor == 1) {
            this.Inicializar();
        }
    }//GEN-LAST:event_txtCod_SeccionActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        this.Agregar();
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        this.Editar('M');
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        this.Editar('E');
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void btnGrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrabarActionPerformed
        this.Grabar();
    }//GEN-LAST:event_btnGrabarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        Inicializar();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        Salir(this);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void cboTipoProductoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cboTipoProductoKeyPressed
        if (evt.getKeyCode() == ClaseTeclas.VK_ENTER()) {
            this.cboIva.grabFocus();
        }
    }//GEN-LAST:event_cboTipoProductoKeyPressed

    private void cboTipoProductoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cboTipoProductoFocusGained
        this.cboTipoProducto.setPopupVisible(true);
    }//GEN-LAST:event_cboTipoProductoFocusGained

    private void cboIvaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cboIvaKeyPressed
        if (evt.getKeyCode() == ClaseTeclas.VK_ENTER()) {
            this.txtEstante.grabFocus();
        }
    }//GEN-LAST:event_cboIvaKeyPressed

    private void cboIvaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cboIvaFocusGained
        this.cboIva.setPopupVisible(true);
    }//GEN-LAST:event_cboIvaFocusGained

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.app.botones.btnBorrar btnBorrar;
    private com.app.botones.btnCancelar btnCancelar;
    private com.app.botones.btnGrabar btnGrabar;
    private com.app.botones.btnImagen btnImagen1;
    private com.app.botones.btnEditar btnModificar;
    private com.app.botones.btnNuevo btnNuevo;
    private com.app.botones.btnSalir btnSalir;
    private com.app.paleta.combo cboIva;
    private com.app.paleta.combo cboTipoProducto;
    private javax.swing.JCheckBox jCheckControlado;
    private javax.swing.JCheckBox jCheckPedesedero;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelBotones;
    private javax.swing.JPanel jPanelDatos;
    private javax.swing.JPanel jPanelTitulo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTabbedPane jTab;
    private javax.swing.JLabel textNom_Envace;
    private javax.swing.JLabel textNom_Linea;
    private javax.swing.JLabel textNom_Marca;
    private javax.swing.JLabel textNom_Procedencia;
    private javax.swing.JLabel textNom_Seccion;
    private javax.swing.JLabel textTitulo;
    private com.app.paleta.txtTexto txtCod_Barra;
    private com.app.paleta.txtCodigo txtCod_Envace;
    private com.app.paleta.txtCodigo txtCod_Linea;
    private com.app.paleta.txtCodigo txtCod_Marca;
    private com.app.paleta.txtCodigo txtCod_Procedencia;
    private com.app.paleta.txtCodigo txtCod_Producto;
    private com.app.paleta.txtCodigo txtCod_Seccion;
    private com.app.paleta.txtNumeros txtColumna;
    private javax.swing.JTextArea txtComentario;
    private com.app.paleta.txtNumeros txtCosto_Actual;
    private com.app.paleta.txtNumeros txtCosto_Inicial;
    private com.app.paleta.txtNumeros txtDescuento;
    private com.app.paleta.txtNumeros txtEstante;
    private com.app.paleta.txtNumeros txtFactor;
    private com.app.paleta.txtNumeros txtFila;
    private com.app.paleta.txtTexto txtNombre_Producto;
    private com.app.paleta.txtNumeros txtPrecioV_Actual;
    private com.app.paleta.txtNumeros txtPrecioV_Inicial;
    private com.app.paleta.txtNumeros txtStockMinimo;
    // End of variables declaration//GEN-END:variables

    @Override
    public void Inicializar() {
        ClaseCampos.setTextNull(jPanelDatos);
        ClaseCampos.setEnabled(jPanelDatos, false);
        this.vTipo = 0;
        this.recuperado = false;
        this.jTab.setSelectedIndex(0);
        this.jTab.setEnabledAt(1, false);
        this.txtComentario.setEnabled(false);
        this.txtComentario.setText("");
        this.textNom_Envace.setText("");
        this.textNom_Linea.setText("");
        this.textNom_Marca.setText("");
        this.textNom_Seccion.setText("");
        this.textNom_Procedencia.setText("");
        this.btnNuevo.setEnabled(Agrega_OK);
        this.btnModificar.setEnabled(Modifica_OK);
        this.btnBorrar.setEnabled(Borra_OK);
        this.btnGrabar.setEnabled(false);
        this.btnCancelar.setEnabled(false);
        this.btnSalir.setEnabled(true);
        this.txtCod_Producto.setBuscar(true);
        if (this.btnNuevo.isEnabled()) {
            this.btnNuevo.grabFocus();
        } else if (this.btnModificar.isEnabled()) {
            this.btnModificar.grabFocus();
        } else if (this.btnBorrar.isEnabled()) {
            this.btnBorrar.grabFocus();
        } else {
            this.btnSalir.grabFocus();
        }
    }

    @Override
    public void Agregar() {
        this.jTab.setSelectedIndex(0);
        this.jTab.setEnabledAt(1, false);
        if (this.txtCod_Producto.autoNumerico()) {
            ClaseBotones.modoEdicionABM(btnNuevo, btnModificar, btnBorrar, btnGrabar, btnCancelar, btnSalir, false);
            ClaseCampos.setEnabled(jPanelDatos, true);
            this.txtComentario.setEnabled(true);
            this.txtCosto_Actual.setEnabled(false);
            this.txtPrecioV_Actual.setEnabled(false);
            this.btnGrabar.setEnabled(false);
            this.txtCod_Producto.setBuscar(false);
            this.txtNombre_Producto.setEnabled(true);
            Operacion = 'A';
            this.txtCod_Producto.setEnabled(false);
            this.txtNombre_Producto.grabFocus();
        } else {
            Inicializar();
        }
    }

    @Override
    public void Editar(char c) {
        Operacion = c;
        ClaseBotones.modoEdicionABM(btnNuevo, btnModificar, btnBorrar, btnGrabar, btnCancelar, btnSalir, false);
        this.txtCod_Producto.setEnabled(true);
        this.txtCod_Barra.setEnabled(true);
        this.btnGrabar.setEnabled(false);
        this.txtCod_Producto.grabFocus();
    }

    @Override
    public void Grabar() {
        if (Operacion == 'A') {
            if (MensajeSistema.Guardar(this)) {
                if (getConexion.insertar(this.txtCod_Producto.getBdTabla(),
                        new String[]{EMP_CODIGO, this.txtCod_Producto.getBdCodigo(), "Bar_Codigo", this.txtCod_Producto.getBdDescrip(),
                            txtCod_Linea.getBdCodigo(), txtCod_Procedencia.getBdCodigo(), txtCod_Envace.getBdCodigo(),
                            txtCod_Marca.getBdCodigo(), txtCod_Seccion.getBdCodigo(), "peresedero", "controlado", "ubi_estante", "ubi_columna",
                            "ubi_fila", "TIva_Codigo", "TProd_Codigo", "factor", "descuento", "costo_inicial",
                            "venta_inicial", "costo_actual", "venta_actual", "comentario", "stock_minimo", "Usu_Codigo"},
                        new String[]{Configuracion.getEMP_CODIGO(), this.txtCod_Producto.getText(),
                            this.txtCod_Barra.getText(), this.txtNombre_Producto.getText(), this.txtCod_Linea.getText(),
                            this.txtCod_Procedencia.getText(), this.txtCod_Envace.getText(), this.txtCod_Marca.getText(), this.txtCod_Seccion.getText(),
                            this.jCheckPedesedero.isSelected() ? "1" : "2", this.jCheckControlado.isSelected() ? "1" : "2",
                            this.txtEstante.getNumeroString(), this.txtColumna.getNumeroString(), this.txtFila.getNumeroString(),
                            this.cboIva.getSelectCodigo(), this.cboTipoProducto.getSelectCodigo(), this.txtFactor.getNumeroString(),
                            this.txtDescuento.getNumeroString(),this.txtCosto_Inicial.getNumeroString(),this.txtPrecioV_Inicial.getNumeroString(),
                            this.txtCosto_Actual.getNumeroString(), this.txtPrecioV_Actual.getNumeroString(),
                            this.txtComentario.getText().trim(), this.txtStockMinimo.getNumeroString(), Configuracion.getUSU_CODIGO()})) {
                }
            }
        } else {
            if (MensajeSistema.Modificar(this)) {
                getConexion.actualizar(this.txtCod_Producto.getBdTabla(),
                        new String[]{"Bar_Codigo", this.txtCod_Producto.getBdDescrip(), txtCod_Linea.getBdCodigo(), txtCod_Procedencia.getBdCodigo(),
                            txtCod_Envace.getBdCodigo(), txtCod_Marca.getBdCodigo(), txtCod_Seccion.getBdCodigo(), "peresedero", "controlado", "ubi_estante",
                            "ubi_columna", "ubi_fila", "TIva_Codigo", "TProd_Codigo", "factor", "descuento", "costo_actual", "venta_actual",
                            "comentario", "stock_minimo"},
                        new String[]{this.txtCod_Barra.getText(), this.txtNombre_Producto.getText(), this.txtCod_Linea.getText(),
                            this.txtCod_Procedencia.getText(), this.txtCod_Envace.getText(), this.txtCod_Marca.getText(), this.txtCod_Seccion.getText(),
                            this.jCheckPedesedero.isSelected() ? "1" : "2", this.jCheckControlado.isSelected() ? "1" : "2",
                            this.txtEstante.getNumeroString(), this.txtColumna.getNumeroString(), this.txtFila.getNumeroString(),
                            this.cboIva.getSelectCodigo(), this.cboTipoProducto.getSelectCodigo(), this.txtFactor.getNumeroString(),
                            this.txtDescuento.getNumeroString(), this.txtCosto_Actual.getNumeroString(), this.txtPrecioV_Actual.getNumeroString(),
                            this.txtComentario.getText().trim(), this.txtStockMinimo.getNumeroString()},
                        new String[]{this.EMP_CODIGO, this.txtCod_Producto.getBdCodigo()},
                        new String[]{Configuracion.getEMP_CODIGO(), this.txtCod_Producto.getText()});
            }
        }
        Inicializar();
    }

    @Override
    public void RecuperarDatos(String codigo) {
        String[] resultado = getConexion.getDescripciones("vst_" + this.txtCod_Producto.getBdTabla(),
                new String[]{this.txtCod_Producto.getBdCodigo(), "Bar_Codigo", this.txtCod_Producto.getBdDescrip(), txtCod_Linea.getBdCodigo(), txtCod_Linea.getBdDescrip(),
                    txtCod_Procedencia.getBdCodigo(), txtCod_Procedencia.getBdDescrip(), txtCod_Envace.getBdCodigo(), txtCod_Envace.getBdDescrip(),
                    txtCod_Marca.getBdCodigo(), txtCod_Marca.getBdDescrip(), txtCod_Seccion.getBdCodigo(), txtCod_Seccion.getBdDescrip(),
                    "peresedero", "controlado", "ubi_estante", "ubi_columna", "ubi_fila", "TIva_Codigo", "TProd_Codigo", "factor", "descuento",
                    "costo_inicial", "venta_inicial", "costo_actual", "venta_actual", "comentario", "stock_minimo"},
                new String[]{this.EMP_CODIGO, vTipo == 1 ? this.txtCod_Producto.getBdCodigo() : "Bar_Codigo"},
                new String[]{Configuracion.getEMP_CODIGO(), codigo});
        if (resultado[0] != null) {
            this.txtCod_Producto.setText(resultado[0]);
            this.txtCod_Barra.setText(resultado[1]);
            this.txtNombre_Producto.setText(resultado[2]);
            this.txtCod_Linea.setText(resultado[3]);
            this.textNom_Linea.setText(resultado[4]);
            this.txtCod_Procedencia.setText(resultado[5]);
            this.textNom_Procedencia.setText(resultado[6]);
            this.txtCod_Envace.setText(resultado[7]);
            this.textNom_Envace.setText(resultado[8]);
            this.txtCod_Marca.setText(resultado[9]);
            this.textNom_Marca.setText(resultado[10]);
            this.txtCod_Seccion.setText(resultado[11]);
            this.textNom_Seccion.setText(resultado[12]);
            this.jCheckPedesedero.setSelected("1".equals(resultado[13]));
            this.jCheckControlado.setSelected("1".equals(resultado[14]));
            this.txtEstante.setText(resultado[15]);
            this.txtColumna.setText(resultado[16]);
            this.txtFila.setText(resultado[17]);
            this.cboIva.setSelectCodigo(resultado[18]);
            this.cboTipoProducto.setSelectCodigo(resultado[19]);
            this.txtFactor.setText(resultado[20]);
            this.txtDescuento.setText(resultado[21]);
            this.txtCosto_Inicial.setNumero(resultado[22]);
            this.txtPrecioV_Inicial.setNumero(resultado[23]);
            this.txtCosto_Actual.setNumero(resultado[24]);
            this.txtPrecioV_Actual.setNumero(resultado[25]);
            this.txtComentario.setText(resultado[26]);
            this.txtStockMinimo.setText(resultado[27]);
            if (Operacion == 'E') {
                this.txtCod_Producto.Borrar();
                Inicializar();
            } else {
                this.recuperado = true;
                ClaseCampos.setEnabled(jPanelDatos, true);
                this.txtCosto_Inicial.setEnabled(false);
                this.txtPrecioV_Inicial.setEnabled(false);
                this.txtCod_Producto.setEnabled(false);
                this.txtCod_Barra.setEnabled(false);
                this.txtComentario.setEnabled(true);
                this.txtNombre_Producto.grabFocus();
            }
        } else {
            if (MensajeSistema.ConsultaSQLVacio(this)) {
                this.recuperado = false;
                if (vTipo == 1) {
                    this.txtCod_Producto.setText("");
                    this.txtCod_Producto.setEnabled(true);
                    this.txtCod_Producto.grabFocus();
                } else {
                    this.txtCod_Barra.setText("");
                    this.txtCod_Barra.setEnabled(true);
                    this.txtCod_Barra.grabFocus();
                }
            } else {
                this.Inicializar();
            }
        }
    }
}
